Repository mojohaus/versions, pull requests merged in 2022-10, with the labels that each got.

#733 #454: Introducing "infinity-like" range calculus for dependency range computation
  src/main/java/org/codehaus/mojo/versions/AbstractVersionsDependencyUpdaterMojo.java
  src/main/java/org/codehaus/mojo/versions/AbstractVersionsReportRenderer.java
  src/main/java/org/codehaus/mojo/versions/AbstractVersionsUpdaterMojo.java
  src/main/java/org/codehaus/mojo/versions/DependencyUpdatesReport.java
  src/main/java/org/codehaus/mojo/versions/DisplayDependencyUpdatesMojo.java
  src/main/java/org/codehaus/mojo/versions/SetMojo.java
  src/main/java/org/codehaus/mojo/versions/api/AbstractVersionDetails.java
  src/main/java/org/codehaus/mojo/versions/api/PomHelper.java
  src/main/java/org/codehaus/mojo/versions/api/Segment.java
  src/main/java/org/codehaus/mojo/versions/api/VersionDetails.java
  src/main/java/org/codehaus/mojo/versions/ordering/AbstractVersionComparator.java
  src/main/java/org/codehaus/mojo/versions/ordering/BoundArtifactVersion.java
  src/main/java/org/codehaus/mojo/versions/ordering/ComparableVersion.java
  src/main/java/org/codehaus/mojo/versions/ordering/MavenVersionComparator.java
  src/main/java/org/codehaus/mojo/versions/ordering/VersionComparator.java
  src/site/apt/examples/advancing-dependency-versions.apt.vm
  src/site/apt/examples/display-plugin-updates.apt
  src/test/java/org/codehaus/mojo/versions/DependencyUpdatesReportTest.java
  src/test/java/org/codehaus/mojo/versions/DisplayDependencyUpdatesMojoTest.java
  src/test/java/org/codehaus/mojo/versions/UseLatestReleasesMojoTest.java
  src/test/java/org/codehaus/mojo/versions/api/ArtifactVersionsTest.java
  src/test/java/org/codehaus/mojo/versions/ordering/MavenVersionComparatorTest.java
  src/test/java/org/codehaus/mojo/versions/ordering/MercuryVersionComparatorTest.java
  src/test/java/org/codehaus/mojo/versions/ordering/NumericVersionComparatorTest.java
  src/test/java/org/codehaus/mojo/versions/utils/MockUtils.java
Labels: bug

#735 #729: Ignoring the flipper
  pom.xml
Labels: maintenance

#734 #725: Migrating index.apt to markdown
  src/site/apt/index.apt
  src/site/markdown/index.md
Labels: documentation

#728 Deploy project snapshots to OSS after each commit
  .github/workflows/maven.yml
Labels: build

#737 #499: Add segment selection to update parent
  src/it/it-update-parent-002/invoker.properties
  src/it/it-update-parent-002/pom.xml
  src/it/it-update-parent-002/verify.bsh
  src/it/it-update-parent-003/invoker.properties
  src/it/it-update-parent-003/pom.xml
  src/it/it-update-parent-003/verify.bsh
  src/main/java/org/codehaus/mojo/versions/AbstractVersionsUpdaterMojo.java
  src/main/java/org/codehaus/mojo/versions/UpdateParentMojo.java
  src/main/java/org/codehaus/mojo/versions/api/AbstractVersionDetails.java
  src/test/java/org/codehaus/mojo/versions/UpdateParentMojoTest.java
Labels: enhancement

#739 #725 Migrating usage.apt.vm to Markdown
  src/site/apt/usage.apt.vm
  src/site/markdown/usage.md.vm
Labels: documentation

#750 Add a link to the actual Maven versioning specification
  src/site/markdown/version-rules.md.vm
Labels: documentation

#747 #725: Migrating Compare dependency versions
  src/site/apt/examples/compare-dependencies.apt
  src/site/markdown/compare-dependencies.md
Labels: documentation

#749 Caching update information in reports to increase performance
  src/main/java/org/codehaus/mojo/versions/api/ArtifactVersionsCache.java
  src/main/java/org/codehaus/mojo/versions/reporting/AbstractVersionsReportRenderer.java
  src/main/java/org/codehaus/mojo/versions/reporting/DependencyUpdatesReportRenderer.java
  src/main/java/org/codehaus/mojo/versions/reporting/PluginUpdatesReportRenderer.java
  src/main/java/org/codehaus/mojo/versions/reporting/PropertyUpdatesReportRenderer.java
Labels: enhancement

#748 #725: Migrating display-dependency-updates.apt
  src/site/markdown/display-dependency-updates.md
Labels: documentation

#745 #283: allowMinorUpdates false should imply allowMajorUpdates false
  src/main/java/org/codehaus/mojo/versions/AbstractVersionsUpdaterMojo.java
  src/main/java/org/codehaus/mojo/versions/DisplayDependencyUpdatesMojo.java
  src/main/java/org/codehaus/mojo/versions/DisplayPropertyUpdatesMojo.java
  src/main/java/org/codehaus/mojo/versions/ResolveRangesMojo.java
  src/main/java/org/codehaus/mojo/versions/UpdateParentMojo.java
  src/main/java/org/codehaus/mojo/versions/UpdatePropertiesMojo.java
  src/main/java/org/codehaus/mojo/versions/UpdatePropertyMojo.java
  src/main/java/org/codehaus/mojo/versions/UseLatestReleasesMojo.java
  src/main/java/org/codehaus/mojo/versions/UseLatestSnapshotsMojo.java
  src/main/java/org/codehaus/mojo/versions/UseLatestVersionsMojo.java
  src/main/java/org/codehaus/mojo/versions/UseNextSnapshotsMojo.java
  src/main/java/org/codehaus/mojo/versions/ordering/MajorMinorIncrementalFilter.java
  src/main/java/org/codehaus/mojo/versions/utils/SegmentUtils.java
  src/test/java/org/codehaus/mojo/versions/UpdateParentMojoTest.java
  src/test/java/org/codehaus/mojo/versions/UseLatestVersionsMojoTest.java
  src/test/java/org/codehaus/mojo/versions/ordering/MajorMinorIncrementalFilterTest.java
Labels: enhancement

#751 Adding some of the remaining AbstractVersionDetails methods to the interface
  src/main/java/org/codehaus/mojo/versions/api/AbstractVersionDetails.java
  src/main/java/org/codehaus/mojo/versions/api/VersionDetails.java
Labels: maintenance

#752 #725: Migrating the plugin dependency updates example
  src/site/markdown/examples/advancing-dependency-versions.md.vm
  src/site/markdown/examples/display-plugin-updates.md
  src/site/markdown/faq.md
  src/site/markdown/index.md
  src/site/markdown/usage.md.vm
  src/site/markdown/version-rules.md.vm
Labels: documentation

#753 #454 Use BoundArtifactVersion with UpdatePropertiesMojo
  src/it-repo/dummy-parent5-1.0.0.pom
  src/it-repo/dummy-parent5-2.0.0-rc1.pom
  src/it/it-resolve-ranges-issue-454/invoker.properties
  src/it/it-resolve-ranges-issue-454/pom.xml
  src/it/it-resolve-ranges-issue-454/verify.groovy
  src/it/it-update-parent-issue-454/invoker.properties
  src/it/it-update-parent-issue-454/pom.xml
  src/it/it-update-parent-issue-454/verify.groovy
  src/main/java/org/codehaus/mojo/versions/UpdatePropertiesMojo.java
  src/main/java/org/codehaus/mojo/versions/UpdatePropertyMojo.java
  src/main/java/org/codehaus/mojo/versions/api/PropertyVersions.java
  src/test/java/org/codehaus/mojo/versions/UpdatePropertiesMojoTest.java
  src/test/java/org/codehaus/mojo/versions/UpdatePropertiesMojoTestBase.java
  src/test/java/org/codehaus/mojo/versions/UpdatePropertyMojoTest.java
  src/test/java/org/codehaus/mojo/versions/utils/TestUtils.java
  src/test/resources/org/codehaus/mojo/update-properties/issue-454-pom.xml
Labels: bug

#761 #760: Fixing the reported number of updates
  src/main/java/org/codehaus/mojo/versions/ordering/AbstractVersionComparator.java
  src/test/java/org/codehaus/mojo/versions/DependencyUpdatesReportMojoTest.java
  src/test/java/org/codehaus/mojo/versions/ordering/MavenVersionComparatorTest.java
  src/test/java/org/codehaus/mojo/versions/ordering/MercuryVersionComparatorTest.java
  src/test/java/org/codehaus/mojo/versions/ordering/NumericVersionComparatorTest.java
Labels: bug

#732 Caching, Last Version on XML reports, Remove Oldest
  src/it/it-dependency-updates-report-001/verify.bsh
  src/it/it-dependency-updates-report-002/verify.bsh
  src/it/it-plugin-updates-report-001/verify.bsh
  src/it/it-plugin-updates-report-002/verify.bsh
  src/it/it-plugin-updates-report-003/verify.bsh
  src/main/java/org/codehaus/mojo/versions/api/AbstractVersionDetails.java
  src/main/java/org/codehaus/mojo/versions/api/ArtifactVersionsCache.java
  src/main/java/org/codehaus/mojo/versions/api/VersionDetails.java
  src/main/java/org/codehaus/mojo/versions/reporting/AbstractVersionsReportRenderer.java
  src/main/java/org/codehaus/mojo/versions/reporting/DependencyUpdatesReportRenderer.java
  src/main/java/org/codehaus/mojo/versions/reporting/OverviewStats.java
  src/main/java/org/codehaus/mojo/versions/reporting/PluginOverviewStats.java
  src/main/java/org/codehaus/mojo/versions/reporting/PluginUpdatesReportRenderer.java
  src/main/java/org/codehaus/mojo/versions/reporting/PropertyUpdatesReportRenderer.java
  src/main/java/org/codehaus/mojo/versions/reporting/VersionsReportRendererBase.java
  src/main/java/org/codehaus/mojo/versions/xml/DependencyUpdatesXmlReportRenderer.java
  src/main/java/org/codehaus/mojo/versions/xml/PluginUpdatesXmlReportRenderer.java
  src/main/mdo/dependency-updates-report.mdo
  src/main/mdo/plugin-updates-report.mdo
  src/main/resources/dependency-updates-report.properties
  src/main/resources/parent-updates-report.properties
  src/main/resources/plugin-updates-report.properties
  src/main/resources/property-updates-report.properties
  src/test/java/org/codehaus/mojo/versions/DependencyUpdatesXmlRendererTest.java
  src/test/java/org/codehaus/mojo/versions/PluginUpdatesXmlRendererTest.java
  src/test/java/org/codehaus/mojo/versions/api/ArtifactVersionsTest.java
Labels: enhancement

#759 #367: Include parent projects in property resolution
  src/main/java/org/codehaus/mojo/versions/api/PomHelper.java
  src/test/java/org/codehaus/mojo/versions/DisplayPropertyUpdatesMojoTest.java
  src/test/java/org/codehaus/mojo/versions/utils/TestUtils.java
  src/test/resources/org/codehaus/mojo/display-property-updates/issue-367/child/pom.xml
  src/test/resources/org/codehaus/mojo/display-property-updates/issue-367/pom.xml
Labels: enhancement

#764 Remove redundant logs in info level
  src/main/java/org/codehaus/mojo/versions/utils/SegmentUtils.java
Labels: enhancement

#763 #762 Fix Plugin Report and Success/Warning icons, counts
  src/main/java/org/codehaus/mojo/versions/reporting/AbstractVersionsReportRenderer.java
  src/main/java/org/codehaus/mojo/versions/reporting/PluginUpdatesReportRenderer.java
Labels: bug

#765 Minor enhancement: use streams API in getNewestUpdates and getVersions
  src/main/java/org/codehaus/mojo/versions/api/AbstractVersionDetails.java
Labels: maintenance

#766 Build Modello improvement, change namespace for xsd
  pom.xml
  src/main/mdo/dependency-updates-report.mdo
  src/main/mdo/plugin-updates-report.mdo
  src/main/mdo/rule.mdo
  src/site/markdown/version-rules.md.vm
  src/site/markdown/xsd/index.md
  src/site/resources/xsd/rule-2.0.0.xsd
  src/site/site.xml
Labels: enhancement

#770 Fixing #769
  src/main/java/org/codehaus/mojo/versions/utils/SegmentUtils.java
  src/test/java/org/codehaus/mojo/versions/utils/SegmentUtilsTest.java
Labels: bug

#775 Bump parent version from 70 to 71
  pom.xml
Labels: dependencies

#777 Resolves #776: onlyUpgradable change the filter to versions where the current version is not the latest one
  src/main/java/org/codehaus/mojo/versions/DependencyUpdatesReportMojo.java
  src/main/java/org/codehaus/mojo/versions/PluginUpdatesReportMojo.java
  src/main/java/org/codehaus/mojo/versions/api/AbstractVersionDetails.java
  src/main/java/org/codehaus/mojo/versions/api/DefaultVersionsHelper.java
  src/main/java/org/codehaus/mojo/versions/api/VersionDetails.java
  src/test/java/org/codehaus/mojo/versions/DependencyUpdatesReportMojoTest.java
  src/test/java/org/codehaus/mojo/versions/PluginUpdatesReportMojoTest.java
Labels: bug

#791 Resolves #790: Fix update scope determination in DisplayDependencyUpdatesMojo
  src/main/java/org/codehaus/mojo/versions/DisplayDependencyUpdatesMojo.java
  src/test/java/org/codehaus/mojo/versions/DisplayDependencyUpdatesMojoTest.java
Labels: bug

#798 Upgrade com.fasterxml.woodstox:woodstox-core to 6.4.0
  pom.xml
Labels: dependencies

#795 Resolves #793: Added includeParent to DisplayPropertyUpdates and PropertyUpdatesReport
  src/main/java/org/codehaus/mojo/versions/CompareDependenciesMojo.java
  src/main/java/org/codehaus/mojo/versions/DisplayPropertyUpdatesMojo.java
  src/main/java/org/codehaus/mojo/versions/PropertyUpdatesReportMojo.java
  src/main/java/org/codehaus/mojo/versions/ResolveRangesMojo.java
  src/main/java/org/codehaus/mojo/versions/SetPropertyMojo.java
  src/main/java/org/codehaus/mojo/versions/UpdatePropertiesMojo.java
  src/main/java/org/codehaus/mojo/versions/UpdatePropertyMojo.java
  src/main/java/org/codehaus/mojo/versions/api/DefaultVersionsHelper.java
  src/main/java/org/codehaus/mojo/versions/api/PomHelper.java
  src/main/java/org/codehaus/mojo/versions/api/VersionsHelper.java
  src/test/java/org/codehaus/mojo/versions/DisplayPropertyUpdatesMojoTest.java
  src/test/java/org/codehaus/mojo/versions/PropertyUpdatesReportMojoTest.java
  src/test/java/org/codehaus/mojo/versions/api/DefaultVersionsHelperTest.java
Labels: enhancement

#797 #614 resolve version from model properties if necessary
  src/main/java/org/codehaus/mojo/versions/DependencyUpdatesReportMojo.java
  src/main/java/org/codehaus/mojo/versions/DisplayDependencyUpdatesMojo.java
  src/main/java/org/codehaus/mojo/versions/api/DefaultVersionsHelper.java
  src/main/java/org/codehaus/mojo/versions/api/VersionsHelper.java
  src/test/java/org/codehaus/mojo/versions/DependencyUpdatesReportMojoTest.java
  src/test/java/org/codehaus/mojo/versions/DisplayDependencyUpdatesMojoTest.java
  src/test/resources/org/codehaus/mojo/display-dependency-updates/version-interpolation/pom.xml
Labels: bug
