Repository mojohaus/versions, pull requests merged in 2022-09, with the labels that each got.

#667 Fixing #315: Guarding against newVersion or property being empty if the properties file is not provided
  src/main/java/org/codehaus/mojo/versions/SetPropertyMojo.java
  src/test/java/org/codehaus/mojo/versions/SetPropertyMojoTest.java
  src/test/java/org/codehaus/mojo/versions/utils/BaseMojoTestCase.java
  src/test/resources/org/codehaus/mojo/set-property/null-new-version-pom.xml
  src/test/resources/org/codehaus/mojo/set-property/null-property-pom.xml
Labels: enhancement

#666 Fixing #251: proper handling of InvalidSegmentException and InvalidVersionSpecificationException
  src/main/java/org/codehaus/mojo/versions/AbstractVersionsUpdaterMojo.java
  src/main/java/org/codehaus/mojo/versions/DisplayPropertyUpdatesMojo.java
  src/main/java/org/codehaus/mojo/versions/PluginUpdatesDetails.java
  src/main/java/org/codehaus/mojo/versions/ResolveRangesMojo.java
  src/main/java/org/codehaus/mojo/versions/UpdatePropertiesMojo.java
  src/main/java/org/codehaus/mojo/versions/UpdatePropertyMojo.java
  src/main/java/org/codehaus/mojo/versions/UseLatestReleasesMojo.java
  src/main/java/org/codehaus/mojo/versions/UseLatestSnapshotsMojo.java
  src/main/java/org/codehaus/mojo/versions/UseLatestVersionsMojo.java
  src/main/java/org/codehaus/mojo/versions/UseNextSnapshotsMojo.java
  src/main/java/org/codehaus/mojo/versions/api/AbstractVersionDetails.java
  src/main/java/org/codehaus/mojo/versions/api/PropertyVersions.java
  src/main/java/org/codehaus/mojo/versions/api/UpdateScope.java
  src/main/java/org/codehaus/mojo/versions/api/VersionDetails.java
  src/main/java/org/codehaus/mojo/versions/ordering/AbstractVersionComparator.java
  src/main/java/org/codehaus/mojo/versions/ordering/InvalidSegmentException.java
  src/main/java/org/codehaus/mojo/versions/ordering/MavenVersionComparator.java
  src/main/java/org/codehaus/mojo/versions/ordering/MercuryVersionComparator.java
  src/main/java/org/codehaus/mojo/versions/ordering/NumericVersionComparator.java
  src/main/java/org/codehaus/mojo/versions/ordering/VersionComparator.java
  src/test/java/org/codehaus/mojo/versions/UseLatestVersionsMojoTest.java
  src/test/java/org/codehaus/mojo/versions/ordering/MavenVersionComparatorTest.java
  src/test/java/org/codehaus/mojo/versions/ordering/VersionComparatorsTest.java
Labels: enhancement

#671 Fixing #670: restoring allowSnapshots which was disabled in PR #665
  src/it-repo/dummy-parent4-70.pom
  src/it-repo/dummy-parent4-71-SNAPSHOT.pom
  src/it/it-update-parent-005-issue-670/invoker.properties
  src/it/it-update-parent-005-issue-670/pom.xml
  src/it/it-update-parent-005-issue-670/verify.groovy
  src/main/java/org/codehaus/mojo/versions/UpdateParentMojo.java
  src/test/java/org/codehaus/mojo/versions/UpdateParentMojoTest.java
Labels: bug

#675 #673: Fixing NPE in UseDepVersionMojo caused by PatternIncludesArtifactFilter expecting a non-null classifier when using wildcards
  pom.xml
  src/test/java/org/codehaus/mojo/versions/UseDepVersionMojoTest.java
  src/test/java/org/codehaus/mojo/versions/utils/BaseMojoTestCase.java
  src/test/resources/org/codehaus/mojo/use-dep-version/issue-637-pom.xml
Labels: bug

#683 Fixed #682: Restoring the ability to provide an empty "newVersion" argument
  src/main/java/org/codehaus/mojo/versions/SetPropertyMojo.java
  src/test/java/org/codehaus/mojo/versions/SetPropertyMojoTest.java
  src/test/java/org/codehaus/mojo/versions/utils/BaseMojoTestCase.java
  src/test/resources/org/codehaus/mojo/set-property/null-property-pom.xml
  src/test/resources/org/codehaus/mojo/set-property/pom.xml
Labels: bug

#688 Issue 687 promote dependency builder
  src/main/java/org/codehaus/mojo/versions/AbstractVersionsDependencyUpdaterMojo.java
  src/main/java/org/codehaus/mojo/versions/CompareDependenciesMojo.java
  src/main/java/org/codehaus/mojo/versions/DisplayParentUpdatesMojo.java
  src/main/java/org/codehaus/mojo/versions/DisplayPluginUpdatesMojo.java
  src/main/java/org/codehaus/mojo/versions/UpdateParentMojo.java
  src/main/java/org/codehaus/mojo/versions/UseLatestReleasesMojo.java
  src/main/java/org/codehaus/mojo/versions/UseLatestSnapshotsMojo.java
  src/main/java/org/codehaus/mojo/versions/UseLatestVersionsMojo.java
  src/main/java/org/codehaus/mojo/versions/UseReleasesMojo.java
  src/main/java/org/codehaus/mojo/versions/api/DefaultVersionsHelper.java
  src/main/java/org/codehaus/mojo/versions/api/PomHelper.java
  src/main/java/org/codehaus/mojo/versions/utils/DependencyBuilder.java
  src/test/java/org/codehaus/mojo/versions/DependencyBuilder.java
  src/test/java/org/codehaus/mojo/versions/DependencyUpdatesReportTest.java
  src/test/java/org/codehaus/mojo/versions/UseLatestVersionsMojoTest.java
  src/test/java/org/codehaus/mojo/versions/filtering/DependencyFilterTest.java
  src/test/java/org/codehaus/mojo/versions/filtering/TokenizedMatcherTest.java
Labels: maintenance

#689 Issue 610 update-parent: add a possibility to skip version resolution and enforce a parent version
  src/it/it-update-parent-005-issue-610/invoker.properties
  src/it/it-update-parent-005-issue-610/pom.xml
  src/it/it-update-parent-005-issue-610/verify.groovy
  src/main/java/org/codehaus/mojo/versions/UpdateParentMojo.java
  src/test/java/org/codehaus/mojo/versions/UpdateParentMojoTest.java
Labels: enhancement

#694 Issue 342 scm set tag add new elements
  src/main/java/org/codehaus/mojo/versions/SetScmTagMojo.java
  src/main/java/org/codehaus/mojo/versions/api/PomHelper.java
  src/test/java/org/codehaus/mojo/versions/SetScmTagMojoTest.java
  src/test/java/org/codehaus/mojo/versions/api/PomHelperTest.java
  src/test/java/org/codehaus/mojo/versions/utils/ModifiedPomXMLEventReaderUtils.java
  src/test/resources/org/codehaus/mojo/set-scm-tag/issue-342-pom.xml
  src/test/resources/org/codehaus/mojo/set-scm-tag/pom.xml
Labels: enhancement

#701 Fixing #700: Adapting SetScmTagMojoTest to work without BaseMojoTestCase
  src/test/java/org/codehaus/mojo/versions/SetScmTagMojoTest.java
  src/test/resources/org/codehaus/mojo/set-scm-tag/issue-342-pom.xml
  src/test/resources/org/codehaus/mojo/set-scm-tag/pom.xml
Labels: maintenance

#705 emove unused and deprecated Mojo annotation requiresProject. A…
  src/main/java/org/codehaus/mojo/versions/CommitMojo.java
  src/main/java/org/codehaus/mojo/versions/CompareDependenciesMojo.java
  src/main/java/org/codehaus/mojo/versions/DisplayDependencyUpdatesMojo.java
  src/main/java/org/codehaus/mojo/versions/DisplayParentUpdatesMojo.java
  src/main/java/org/codehaus/mojo/versions/DisplayPluginUpdatesMojo.java
  src/main/java/org/codehaus/mojo/versions/DisplayPropertyUpdatesMojo.java
  src/main/java/org/codehaus/mojo/versions/ForceReleasesMojo.java
  src/main/java/org/codehaus/mojo/versions/LockSnapshotsMojo.java
  src/main/java/org/codehaus/mojo/versions/PropertyUpdatesReport.java
  src/main/java/org/codehaus/mojo/versions/ResolveRangesMojo.java
  src/main/java/org/codehaus/mojo/versions/RevertMojo.java
  src/main/java/org/codehaus/mojo/versions/SetMojo.java
  src/main/java/org/codehaus/mojo/versions/SetPropertyMojo.java
  src/main/java/org/codehaus/mojo/versions/SetScmTagMojo.java
  src/main/java/org/codehaus/mojo/versions/UnlockSnapshotsMojo.java
  src/main/java/org/codehaus/mojo/versions/UpdateChildModulesMojo.java
  src/main/java/org/codehaus/mojo/versions/UpdateParentMojo.java
  src/main/java/org/codehaus/mojo/versions/UpdatePropertiesMojo.java
  src/main/java/org/codehaus/mojo/versions/UpdatePropertyMojo.java
  src/main/java/org/codehaus/mojo/versions/UseDepVersionMojo.java
  src/main/java/org/codehaus/mojo/versions/UseLatestReleasesMojo.java
  src/main/java/org/codehaus/mojo/versions/UseLatestSnapshotsMojo.java
  src/main/java/org/codehaus/mojo/versions/UseLatestVersionsMojo.java
  src/main/java/org/codehaus/mojo/versions/UseNextReleasesMojo.java
  src/main/java/org/codehaus/mojo/versions/UseNextSnapshotsMojo.java
  src/main/java/org/codehaus/mojo/versions/UseNextVersionsMojo.java
  src/main/java/org/codehaus/mojo/versions/UseReactorMojo.java
  src/main/java/org/codehaus/mojo/versions/UseReleasesMojo.java
Labels: maintenance

#708 Further refactoring: replacing segment index with the Segment enum
  src/main/java/org/codehaus/mojo/versions/AbstractVersionsUpdaterMojo.java
  src/main/java/org/codehaus/mojo/versions/DisplayPropertyUpdatesMojo.java
  src/main/java/org/codehaus/mojo/versions/ResolveRangesMojo.java
  src/main/java/org/codehaus/mojo/versions/UpdatePropertiesMojo.java
  src/main/java/org/codehaus/mojo/versions/UpdatePropertyMojo.java
  src/main/java/org/codehaus/mojo/versions/UseLatestReleasesMojo.java
  src/main/java/org/codehaus/mojo/versions/UseLatestSnapshotsMojo.java
  src/main/java/org/codehaus/mojo/versions/UseLatestVersionsMojo.java
  src/main/java/org/codehaus/mojo/versions/UseNextSnapshotsMojo.java
  src/main/java/org/codehaus/mojo/versions/api/AbstractVersionDetails.java
  src/main/java/org/codehaus/mojo/versions/api/PropertyVersions.java
  src/main/java/org/codehaus/mojo/versions/api/Segment.java
  src/main/java/org/codehaus/mojo/versions/ordering/AbstractVersionComparator.java
  src/main/java/org/codehaus/mojo/versions/ordering/InvalidSegmentException.java
  src/main/java/org/codehaus/mojo/versions/ordering/MajorMinorIncrementalFilter.java
  src/main/java/org/codehaus/mojo/versions/ordering/MavenVersionComparator.java
  src/main/java/org/codehaus/mojo/versions/ordering/MercuryVersionComparator.java
  src/main/java/org/codehaus/mojo/versions/ordering/NumericVersionComparator.java
  src/main/java/org/codehaus/mojo/versions/ordering/VersionComparator.java
  src/test/java/org/codehaus/mojo/versions/ordering/MavenVersionComparatorTest.java
  src/test/java/org/codehaus/mojo/versions/ordering/MercuryVersionComparatorTest.java
  src/test/java/org/codehaus/mojo/versions/ordering/NumericVersionComparatorTest.java
  src/test/java/org/codehaus/mojo/versions/ordering/VersionComparatorsTest.java
Labels: maintenance

#707 Quick fix reported by IDE improvements
  src/main/java/org/codehaus/mojo/versions/AbstractVersionsDependencyUpdaterMojo.java
  src/main/java/org/codehaus/mojo/versions/CompareDependenciesMojo.java
  src/main/java/org/codehaus/mojo/versions/DependencyUpdatesReport.java
  src/main/java/org/codehaus/mojo/versions/DisplayDependencyUpdatesMojo.java
  src/main/java/org/codehaus/mojo/versions/DisplayPluginUpdatesMojo.java
  src/main/java/org/codehaus/mojo/versions/PluginUpdatesRenderer.java
  src/main/java/org/codehaus/mojo/versions/SetMojo.java
  src/main/java/org/codehaus/mojo/versions/UpdateParentMojo.java
  src/main/java/org/codehaus/mojo/versions/UseLatestReleasesMojo.java
  src/main/java/org/codehaus/mojo/versions/UseReactorMojo.java
  src/main/java/org/codehaus/mojo/versions/api/DefaultVersionsHelper.java
  src/main/java/org/codehaus/mojo/versions/api/PomHelper.java
  src/main/java/org/codehaus/mojo/versions/api/PropertyVersions.java
  src/main/java/org/codehaus/mojo/versions/ordering/MercuryVersionComparator.java
  src/main/java/org/codehaus/mojo/versions/utils/PropertiesVersionsFileReader.java
  src/test/java/org/codehaus/mojo/versions/DisplayDependencyUpdatesMojoTest.java
  src/test/java/org/codehaus/mojo/versions/RewriteWithStAXTest.java
  src/test/java/org/codehaus/mojo/versions/SeparatePatternsForIncludesAnExcludesTest.java
  src/test/java/org/codehaus/mojo/versions/SetMojoTest.java
  src/test/java/org/codehaus/mojo/versions/SetPropertyMojoTest.java
  src/test/java/org/codehaus/mojo/versions/UseDepVersionMojoTest.java
  src/test/java/org/codehaus/mojo/versions/api/DefaultVersionsHelperTest.java
  src/test/java/org/codehaus/mojo/versions/filtering/DependencyFilterTest.java
  src/test/java/org/codehaus/mojo/versions/ordering/VersionComparatorsTest.java
  src/test/java/org/codehaus/mojo/versions/utils/PropertiesVersionsFileReaderTest.java
Labels: maintenance

#672 #632 Fixed lower and upper bounds to keep milestones and rcs in the right majors.
  src/it/it-dependency-updates-report-001/verify.bsh
  src/it/it-plugin-updates-report-001/verify.bsh
  src/main/java/org/codehaus/mojo/versions/AbstractVersionsReportRenderer.java
  src/main/java/org/codehaus/mojo/versions/PluginUpdatesRenderer.java
  src/main/java/org/codehaus/mojo/versions/api/AbstractVersionDetails.java
  src/main/java/org/codehaus/mojo/versions/api/VersionDetails.java
  src/main/java/org/codehaus/mojo/versions/ordering/AbstractVersionComparator.java
  src/main/java/org/codehaus/mojo/versions/ordering/ComparableVersion.java
  src/main/java/org/codehaus/mojo/versions/ordering/MavenVersionComparator.java
  src/test/java/org/codehaus/mojo/versions/ordering/MavenVersionComparatorTest.java
  src/test/java/org/codehaus/mojo/versions/ordering/MercuryVersionComparatorTest.java
  src/test/java/org/codehaus/mojo/versions/ordering/NumericVersionComparatorTest.java
Labels: bug

#712 Implementing #709: removeSnapshot idempotency
  src/main/java/org/codehaus/mojo/versions/SetMojo.java
  src/test/java/org/codehaus/mojo/versions/SetMojoTest.java
  src/test/resources/org/codehaus/mojo/set/remove-snapshot/pom.xml
Labels: bug

#722 #343 Parent updates report
  src/it/it-parent-updates-report-001/invoker.properties
  src/it/it-parent-updates-report-001/module/pom.xml
  src/it/it-parent-updates-report-001/pom.xml
  src/it/it-parent-updates-report-001/src/site/site.xml
  src/it/it-parent-updates-report-001/verify.groovy
  src/main/java/org/codehaus/mojo/versions/DependencyUpdatesRenderer.java
  src/main/java/org/codehaus/mojo/versions/ParentUpdatesReport.java
  src/main/resources/parent-updates-report.properties
  src/site/apt/index.apt
  src/test/java/org/codehaus/mojo/versions/DependencyUpdatesReportTest.java
  src/test/java/org/codehaus/mojo/versions/ParentUpdatesReportTest.java
  src/test/java/org/codehaus/mojo/versions/utils/MockUtils.java
Labels: enhancement

#719 Issue #265: revert mojo to scan child modules instead of relying on maven
  src/it/it-revert-isssue-265/aggregate/pom.xml
  src/it/it-revert-isssue-265/invoker.properties
  src/it/it-revert-isssue-265/module-a/pom.xml
  src/it/it-revert-isssue-265/module-b/pom.xml
  src/it/it-revert-isssue-265/verify.groovy
  src/main/java/org/codehaus/mojo/versions/RevertMojo.java
  src/test/java/org/codehaus/mojo/versions/RevertMojoTest.java
  src/test/resources/org/codehaus/mojo/revert/issue-265/aggregate/pom.xml
  src/test/resources/org/codehaus/mojo/revert/issue-265/aggregate/pom.xml.versionsBackup
  src/test/resources/org/codehaus/mojo/revert/issue-265/module-a/pom.xml
  src/test/resources/org/codehaus/mojo/revert/issue-265/module-a/pom.xml.versionsBackup
  src/test/resources/org/codehaus/mojo/revert/issue-265/module-b/pom.xml
  src/test/resources/org/codehaus/mojo/revert/issue-265/module-b/pom.xml.versionsBackup
Labels: bug
