Repository mojohaus/versions, pull requests merged in 2022-12, with the labels that each got.

#832 Clarification in README - maintained versions, issues and PR creation
  .github/workflows/maven.yml
  README.md
Labels: documentation

#838 Resolves #837: Add includeParent (default true) to UpdatePropertiesMojo
  versions-maven-plugin/src/it/it-update-properties-issue-837/invoker.properties
  versions-maven-plugin/src/it/it-update-properties-issue-837/parent-pom.xml
  versions-maven-plugin/src/it/it-update-properties-issue-837/pom.xml
  versions-maven-plugin/src/it/it-update-properties-issue-837/verify.groovy
  versions-maven-plugin/src/it/it-update-property-issue-837/invoker.properties
  versions-maven-plugin/src/it/it-update-property-issue-837/parent-pom.xml
  versions-maven-plugin/src/it/it-update-property-issue-837/pom.xml
  versions-maven-plugin/src/it/it-update-property-issue-837/verify.groovy
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/AbstractVersionsUpdaterMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UpdatePropertiesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UpdatePropertiesMojoBase.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UpdatePropertyMojo.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/UpdatePropertiesMojoTest.java
  versions-maven-plugin/src/test/resources/org/codehaus/mojo/update-properties/issue-837/parent-pom.xml
  versions-maven-plugin/src/test/resources/org/codehaus/mojo/update-properties/issue-837/pom.xml
Labels: enhancement

#836 #333: aggregated reports
  versions-common/src/main/java/org/codehaus/mojo/versions/api/DefaultVersionsHelper.java
  versions-common/src/main/java/org/codehaus/mojo/versions/api/Property.java
  versions-common/src/main/java/org/codehaus/mojo/versions/utils/PropertyComparator.java
  versions-maven-plugin/src/it-repo/dummy-aggregate-child-333.pom
  versions-maven-plugin/src/it-repo/dummy-aggregate-parent-333.pom
  versions-maven-plugin/src/it/it-dependency-updates-aggregate-report-issue-333/child-one/pom.xml
  versions-maven-plugin/src/it/it-dependency-updates-aggregate-report-issue-333/child-two/pom.xml
  versions-maven-plugin/src/it/it-dependency-updates-aggregate-report-issue-333/invoker.properties
  versions-maven-plugin/src/it/it-dependency-updates-aggregate-report-issue-333/pom.xml
  versions-maven-plugin/src/it/it-dependency-updates-aggregate-report-issue-333/src/site/site.xml
  versions-maven-plugin/src/it/it-dependency-updates-aggregate-report-issue-333/verify.groovy
  versions-maven-plugin/src/it/it-plugin-updates-aggregate-report-issue-333/child-one/pom.xml
  versions-maven-plugin/src/it/it-plugin-updates-aggregate-report-issue-333/child-two/pom.xml
  versions-maven-plugin/src/it/it-plugin-updates-aggregate-report-issue-333/invoker.properties
  versions-maven-plugin/src/it/it-plugin-updates-aggregate-report-issue-333/pom.xml
  versions-maven-plugin/src/it/it-plugin-updates-aggregate-report-issue-333/src/site/site.xml
  versions-maven-plugin/src/it/it-plugin-updates-aggregate-report-issue-333/verify.groovy
  versions-maven-plugin/src/it/it-property-updates-aggregate-report-issue-333/child-one/pom.xml
  versions-maven-plugin/src/it/it-property-updates-aggregate-report-issue-333/child-two/pom.xml
  versions-maven-plugin/src/it/it-property-updates-aggregate-report-issue-333/invoker.properties
  versions-maven-plugin/src/it/it-property-updates-aggregate-report-issue-333/pom.xml
  versions-maven-plugin/src/it/it-property-updates-aggregate-report-issue-333/src/site/site.xml
  versions-maven-plugin/src/it/it-property-updates-aggregate-report-issue-333/verify.groovy
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/AbstractDependencyUpdatesReportMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/AbstractPluginUpdatesReportMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/AbstractPropertyUpdatesReportMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/AbstractVersionsUpdaterMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DependencyUpdatesAggregateReportMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DependencyUpdatesReportMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/PluginUpdatesAggregateReportMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/PluginUpdatesReportMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/PropertyUpdatesAggregateReportMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/PropertyUpdatesReportMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseLatestVersionsMojoBase.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/reporting/ReportRendererFactoryImpl.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/reporting/model/PropertyUpdatesModel.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/reporting/util/AggregateReportUtils.java
  versions-maven-plugin/src/main/resources/dependency-updates-aggregate-report.properties
  versions-maven-plugin/src/main/resources/plugin-updates-aggregate-report.properties
  versions-maven-plugin/src/main/resources/property-updates-aggregate-report.properties
Labels: enhancement

#833 #704: Remove remaining ArtifactRepository leftovers + use version range for VersionsHelper where applicable
  versions-common/pom.xml
  versions-common/src/main/java/org/codehaus/mojo/versions/api/DefaultVersionsHelper.java
  versions-common/src/main/java/org/codehaus/mojo/versions/api/PomHelper.java
  versions-common/src/main/java/org/codehaus/mojo/versions/api/VersionsHelper.java
  versions-enforcer/pom.xml
  versions-enforcer/src/test/java/org/apache/maven/plugins/enforcer/MaxDependencyUpdatesTest.java
  versions-maven-plugin/pom.xml
  versions-maven-plugin/src/it-repo/dummy-maven-plugin-3.1.pom
  versions-maven-plugin/src/it/it-display-plugin-updates-001/pom.xml
  versions-maven-plugin/src/it/it-display-plugin-updates-008/verify.bsh
  versions-maven-plugin/src/it/it-display-plugin-updates-008/verify.groovy
  versions-maven-plugin/src/it/it-display-plugin-updates-012-outputLineWidth/invoker.properties
  versions-maven-plugin/src/it/it-display-plugin-updates-012-outputLineWidth/verify.bsh
  versions-maven-plugin/src/it/it-display-plugin-updates-012-outputLineWidth/verify.groovy
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/AbstractVersionsReport.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/AbstractVersionsUpdaterMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayPluginUpdatesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/RevertMojo.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/PropertyUpdatesReportMojoTest.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/UpdateParentMojoTest.java
  versions-test/pom.xml
Labels: maintenance

#841 #333: aggregated reports site information
  versions-maven-plugin/src/site/markdown/index.md
Labels: enhancement

#842 Wagon should use remote repository instead of proxy repository for repo authentication
  versions-common/src/main/java/org/codehaus/mojo/versions/api/DefaultVersionsHelper.java
Labels: bug

#844 Bump parent version from 71 to 72
  pom.xml
  versions-maven-plugin/pom.xml
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/AbstractVersionsDependencyUpdaterMojo.java
Labels: dependencies

#847 Make Max Dependency enforcer rule as main page of enforcer module
  versions-enforcer/src/site/markdown/index.md.vm
  versions-enforcer/src/site/site.xml
  versions-maven-plugin/src/site/markdown/index.md
Labels: documentation

#849 Resolves #848: Fixing module resolution with nonstandard filenames
  versions-common/src/main/java/org/codehaus/mojo/versions/api/PomHelper.java
  versions-common/src/main/java/org/codehaus/mojo/versions/api/VersionDetails.java
  versions-common/src/main/java/org/codehaus/mojo/versions/api/VersionsHelper.java
  versions-common/src/main/java/org/codehaus/mojo/versions/ordering/ReactorDepthComparator.java
  versions-common/src/main/java/org/codehaus/mojo/versions/utils/MavenProjectUtils.java
  versions-common/src/test/java/org/codehaus/mojo/versions/api/PomHelperTest.java
  versions-maven-plugin/src/it/it-set-issue-848/docs/moduleC/pom.xml
  versions-maven-plugin/src/it/it-set-issue-848/invoker.properties
  versions-maven-plugin/src/it/it-set-issue-848/moduleA/moduleA1.xml
  versions-maven-plugin/src/it/it-set-issue-848/moduleA/moduleA2.xml
  versions-maven-plugin/src/it/it-set-issue-848/moduleB/pom.xml
  versions-maven-plugin/src/it/it-set-issue-848/pom.xml
  versions-maven-plugin/src/it/it-set-issue-848/verify.groovy
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/SetMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UpdateChildModulesMojo.java
Labels: bug

#859 #858 Fix child module resolution for multi-level projects
  versions-common/src/main/java/org/codehaus/mojo/versions/api/PomHelper.java
  versions-common/src/test/java/org/codehaus/mojo/versions/api/PomHelperTest.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/SetMojo.java
Labels: bug

#861 Removes parallelStream use with non-thread safe collectors
  versions-common/src/main/java/org/codehaus/mojo/versions/api/DefaultVersionsHelper.java
  versions-common/src/main/java/org/codehaus/mojo/versions/utils/MavenProjectUtils.java
  versions-enforcer/src/main/java/org/apache/maven/plugins/enforcer/MaxDependencyUpdates.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayDependencyUpdatesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayPluginUpdatesMojo.java
Labels: bug

#856 Resolves #855: Set should evaluate expressions
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/SetMojo.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/SetMojoTest.java
  versions-maven-plugin/src/test/resources/org/codehaus/mojo/set/issue-855/parent-with-property/child/pom.xml
  versions-maven-plugin/src/test/resources/org/codehaus/mojo/set/issue-855/parent-with-property/pom.xml
  versions-maven-plugin/src/test/resources/org/codehaus/mojo/set/issue-855/pom-build-number.xml
  versions-maven-plugin/src/test/resources/org/codehaus/mojo/set/issue-855/pom-multiple-props.xml
  versions-maven-plugin/src/test/resources/org/codehaus/mojo/set/issue-855/pom-simple.xml
  versions-maven-plugin/src/test/resources/org/codehaus/mojo/set/issue-855/pom-undefined.xml
Labels: bug

#862 Resolves #850: Protecting the display-plugin-updates mojo against a NPE in case the effective version of a plugin is not resolved
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayPluginUpdatesMojo.java
Labels: bug

#867 Fixes #866: Require maven 3.2.5
  versions-maven-plugin/pom.xml
Labels: bug

#870 Add a simple cache for ComparableVersions
  versions-common/src/main/java/org/codehaus/mojo/versions/ordering/BoundArtifactVersion.java
  versions-common/src/main/java/org/codehaus/mojo/versions/ordering/ComparableVersion.java
  versions-common/src/main/java/org/codehaus/mojo/versions/ordering/MavenVersionComparator.java
  versions-common/src/main/java/org/codehaus/mojo/versions/ordering/MercuryVersionComparator.java
Labels: enhancement

#875 Project dependencies maintenance - move versions to dependencyManagement
  pom.xml
  versions-common/pom.xml
  versions-enforcer/pom.xml
  versions-maven-plugin/pom.xml
  versions-model-report/pom.xml
  versions-model/pom.xml
  versions-test/pom.xml
Labels: maintenance

#876 Upgrade com.fasterxml.woodstox:woodstox-core to 6.4.0
  pom.xml
Labels: dependencies

#877 Manage transitive dependencies version for security updates
  pom.xml
  versions-maven-plugin/pom.xml
  versions-test/pom.xml
Labels: dependencies

#873 Resolves #872: Make allowSnapshots an explicit argument in lookupDependencyUpdates and in reports
  versions-common/src/main/java/org/codehaus/mojo/versions/api/AbstractVersionDetails.java
  versions-common/src/main/java/org/codehaus/mojo/versions/api/ArtifactVersions.java
  versions-common/src/main/java/org/codehaus/mojo/versions/api/ArtifactVersionsCache.java
  versions-common/src/main/java/org/codehaus/mojo/versions/api/DefaultVersionsHelper.java
  versions-common/src/main/java/org/codehaus/mojo/versions/api/VersionDetails.java
  versions-common/src/main/java/org/codehaus/mojo/versions/api/VersionsHelper.java
  versions-common/src/test/java/org/codehaus/mojo/versions/api/ArtifactVersionsTest.java
  versions-enforcer/src/it-repo/dummy-api-2.2-SNAPSHOT.pom
  versions-enforcer/src/it/it-max-dependency-updates-005/invoker.properties
  versions-enforcer/src/it/it-max-dependency-updates-005/pom.xml
  versions-enforcer/src/it/it-max-dependency-updates-006/invoker.properties
  versions-enforcer/src/it/it-max-dependency-updates-006/pom.xml
  versions-enforcer/src/main/java/org/apache/maven/plugins/enforcer/MaxDependencyUpdates.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/AbstractDependencyUpdatesReportMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/AbstractPluginUpdatesReportMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/AbstractPropertyUpdatesReportMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayDependencyUpdatesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/ParentUpdatesReportMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/reporting/AbstractVersionsReportRenderer.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/reporting/DependencyUpdatesReportRenderer.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/reporting/OverviewStats.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/reporting/ParentUpdatesReportRenderer.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/reporting/PluginOverviewStats.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/reporting/PluginUpdatesReportRenderer.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/reporting/PropertyUpdatesReportRenderer.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/reporting/ReportRendererFactory.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/reporting/ReportRendererFactoryImpl.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/reporting/VersionsReportRendererBase.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/reporting/model/AbstractUpdatesModel.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/reporting/model/DependencyUpdatesModel.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/reporting/model/ParentUpdatesModel.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/reporting/model/PluginUpdatesModel.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/reporting/model/PropertyUpdatesModel.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/reporting/util/ReportRenderer.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/xml/CommonXmlReportRendererUtils.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/xml/DependencyUpdatesXmlReportRenderer.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/xml/PluginUpdatesXmlReportRenderer.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/xml/PropertyUpdatesXmlReportRenderer.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/DependencyUpdatesXmlRendererTest.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/DisplayDependencyUpdatesMojoTest.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/PluginUpdatesXmlRendererTest.java
Labels: bug
