Repository mojohaus/versions, pull requests merged in 2022-11, with the labels that each got.

#799 #794: SetMojo would always change the version of the POM, regardless if a match was found
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/SetMojo.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/SetMojoTest.java
  versions-maven-plugin/src/test/resources/org/codehaus/mojo/set/issue-794/pom.xml
Labels: bug

#805 Resolves #505: getReactorModels using correct module paths when the module name includes pom.xml
  versions-maven-plugin/src/it/it-set-issue-505/invoker.properties
  versions-maven-plugin/src/it/it-set-issue-505/moduleA/moduleB/pom.xml
  versions-maven-plugin/src/it/it-set-issue-505/moduleA/pom.xml
  versions-maven-plugin/src/it/it-set-issue-505/pom.xml
  versions-maven-plugin/src/it/it-set-issue-505/verify.groovy
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/api/PomHelper.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/api/PomHelperTest.java
  versions-maven-plugin/src/test/resources/org/codehaus/mojo/versions/api/issue-505/moduleA/moduleA.xml
  versions-maven-plugin/src/test/resources/org/codehaus/mojo/versions/api/issue-505/moduleA/moduleB/pom.xml
  versions-maven-plugin/src/test/resources/org/codehaus/mojo/versions/api/issue-505/pom.xml
Labels: bug

#808 Resolves #807: Abstracting a common base for UseLatestVersionsMojo and UseLatestReleasesMojo
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/AbstractVersionsDependencyUpdaterMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseLatestReleasesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseLatestVersionsMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseLatestVersionsMojoBase.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/api/AbstractVersionDetails.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/api/VersionDetails.java
  versions-maven-plugin/src/site/markdown/index.md
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/UseLatestVersionsMojoTest.java
Labels: maintenance

#813 Resolves #289: Handle processParent in mojos which support it.
  .gitignore
  versions-common/src/main/java/org/codehaus/mojo/versions/api/ArtifactVersions.java
  versions-common/src/main/java/org/codehaus/mojo/versions/api/ArtifactVersionsCache.java
  versions-common/src/main/java/org/codehaus/mojo/versions/api/PropertyVersions.java
  versions-common/src/main/java/org/codehaus/mojo/versions/recording/ChangeRecorderNull.java
  versions-common/src/main/java/org/codehaus/mojo/versions/recording/ChangeRecorderXML.java
  versions-common/src/main/java/org/codehaus/mojo/versions/utils/DependencyBuilder.java
  versions-common/src/test/java/org/codehaus/mojo/versions/recording/ChangeRecorderXMLTest.java
  versions-maven-plugin/src/it-repo/dummy-with-parent.pom
  versions-maven-plugin/src/it/it-compare-dependencies-issue-289/invoker.properties
  versions-maven-plugin/src/it/it-compare-dependencies-issue-289/pom.xml
  versions-maven-plugin/src/it/it-compare-dependencies-issue-289/verify.groovy
  versions-maven-plugin/src/it/it-use-latest-versions-009/verify.bsh
  versions-maven-plugin/src/it/it-use-latest-versions-009/verify.groovy
  versions-maven-plugin/src/it/it-use-latest-versions-010/verify.bsh
  versions-maven-plugin/src/it/it-use-latest-versions-010/verify.groovy
  versions-maven-plugin/src/it/it-use-latest-versions-011/verify.bsh
  versions-maven-plugin/src/it/it-use-latest-versions-011/verify.groovy
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/AbstractVersionsDependencyUpdaterMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/AbstractVersionsReport.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/AbstractVersionsUpdaterMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/CompareDependenciesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayDependencyUpdatesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/ForceReleasesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/LockSnapshotsMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UnlockSnapshotsMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseDepVersionMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseLatestReleasesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseLatestSnapshotsMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseLatestVersionsMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseLatestVersionsMojoBase.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseNextReleasesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseNextSnapshotsMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseNextVersionsMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseReleasesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/reporting/AbstractVersionsReportRenderer.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/reporting/ReportRendererFactory.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/ForceReleasesMojoTest.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/UseLatestReleasesMojoTest.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/UseLatestVersionsMojoTest.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/UseReleasesMojoTest.java
Labels: bug

#817 Make includeParent false by default to retain backward compatibility.
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayPropertyUpdatesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/PropertyUpdatesReportMojo.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/DisplayPropertyUpdatesMojoTest.java
Labels: enhancement

#818 Site build - gitHub ribbon, stage site
  README.md
  pom.xml
  src/site/site.xml
Labels: maintenance

#825 #704: Removing ArtifactMetadataSource
  pom.xml
  versions-common/src/main/java/org/codehaus/mojo/versions/api/DefaultVersionsHelper.java
  versions-common/src/main/java/org/codehaus/mojo/versions/api/PropertyVersions.java
  versions-common/src/main/java/org/codehaus/mojo/versions/api/PropertyVersionsBuilder.java
  versions-common/src/main/java/org/codehaus/mojo/versions/api/VersionRetrievalException.java
  versions-common/src/main/java/org/codehaus/mojo/versions/api/VersionsHelper.java
  versions-common/src/test/java/org/codehaus/mojo/versions/api/DefaultVersionsHelperTest.java
  versions-common/src/test/java/org/codehaus/mojo/versions/utils/VersionStub.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/AbstractVersionsDependencyUpdaterMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/AbstractVersionsDisplayMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/AbstractVersionsReport.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/AbstractVersionsUpdaterMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/CompareDependenciesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DependencyUpdatesReportMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayDependencyUpdatesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayParentUpdatesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayPluginUpdatesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayPropertyUpdatesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/ForceReleasesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/LockSnapshotsMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/ParentUpdatesReportMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/PluginUpdatesReportMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/PropertyUpdatesReportMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/ResolveRangesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/SetMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/SetPropertyMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/SetScmTagMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UnlockSnapshotsMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UpdateChildModulesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UpdateParentMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UpdatePropertiesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UpdatePropertyMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseDepVersionMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseLatestReleasesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseLatestSnapshotsMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseLatestVersionsMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseLatestVersionsMojoBase.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseNextReleasesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseNextSnapshotsMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseNextVersionsMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseReactorMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseReleasesMojo.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/DependencyUpdatesReportMojoTest.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/DisplayDependencyUpdatesMojoTest.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/DisplayPropertyUpdatesMojoTest.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/ForceReleasesMojoTest.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/ParentUpdatesReportMojoTest.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/PluginUpdatesReportMojoTest.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/PropertyUpdatesReportMojoTest.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/SeparatePatternsForIncludesAnExcludesTest.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/SetPropertyMojoTest.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/UpdateParentMojoTest.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/UpdatePropertiesMojoTestBase.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/UseLatestReleasesMojoTest.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/UseLatestVersionsMojoTest.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/UseReleasesMojoTest.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/utils/MockUtils.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/utils/VersionStub.java
Labels: enhancement

#801 Resolves #387: Provide an enforcer rule to specify the maximum number of allowed dependency updates
  pom.xml
  versions-common/src/main/java/org/codehaus/mojo/versions/api/AbstractVersionDetails.java
  versions-common/src/main/java/org/codehaus/mojo/versions/api/DefaultVersionsHelper.java
  versions-common/src/main/java/org/codehaus/mojo/versions/api/VersionDetails.java
  versions-common/src/main/java/org/codehaus/mojo/versions/api/VersionsHelper.java
  versions-common/src/main/java/org/codehaus/mojo/versions/filtering/DependencyFilter.java
  versions-common/src/main/java/org/codehaus/mojo/versions/ordering/AbstractVersionComparator.java
  versions-common/src/main/java/org/codehaus/mojo/versions/ordering/VersionComparator.java
  versions-common/src/main/java/org/codehaus/mojo/versions/utils/MavenProjectUtils.java
  versions-common/src/test/java/org/codehaus/mojo/versions/api/ArtifactVersionsTest.java
  versions-common/src/test/java/org/codehaus/mojo/versions/utils/PropertiesVersionsFileReaderTest.java
  versions-enforcer/pom.xml
  versions-enforcer/src/it-repo/dummy-api-1.0.pom
  versions-enforcer/src/it-repo/dummy-api-2.0.pom
  versions-enforcer/src/it-repo/dummy-api-2.1.pom
  versions-enforcer/src/it/it-max-dependency-updates-001/invoker.properties
  versions-enforcer/src/it/it-max-dependency-updates-001/pom.xml
  versions-enforcer/src/it/it-max-dependency-updates-002/invoker.properties
  versions-enforcer/src/it/it-max-dependency-updates-002/pom.xml
  versions-enforcer/src/it/it-max-dependency-updates-003/invoker.properties
  versions-enforcer/src/it/it-max-dependency-updates-003/pom.xml
  versions-enforcer/src/it/it-max-dependency-updates-004/invoker.properties
  versions-enforcer/src/it/it-max-dependency-updates-004/pom.xml
  versions-enforcer/src/it/settings.xml
  versions-enforcer/src/main/java/org/apache/maven/plugins/enforcer/MaxDependencyUpdates.java
  versions-enforcer/src/site/markdown/max-dependency-updates.md.vm
  versions-enforcer/src/site/site.xml
  versions-enforcer/src/test/java/org/apache/maven/plugins/enforcer/MaxDependencyUpdatesTest.java
  versions-maven-plugin/pom.xml
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DependencyUpdatesReportMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayDependencyUpdatesMojo.java
  versions-maven-plugin/src/site/markdown/index.md
  versions-test/pom.xml
  versions-test/src/main/java/org/codehaus/mojo/versions/utils/MockUtils.java
  versions-test/src/main/java/org/codehaus/mojo/versions/utils/TestChangeRecorder.java
  versions-test/src/main/java/org/codehaus/mojo/versions/utils/TestUtils.java
  versions-test/src/main/java/org/codehaus/mojo/versions/utils/VersionStub.java
Labels: enhancement

#772 Quality: Refactoring Reports classes
  versions-common/src/main/java/org/codehaus/mojo/versions/api/AbstractVersionDetails.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/reporting/AbstractVersionsReportRenderer.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/reporting/DependencyUpdatesReportRenderer.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/reporting/PluginUpdatesReportRenderer.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/reporting/PropertyUpdatesReportRenderer.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/reporting/VersionsReportRendererBase.java
  versions-maven-plugin/src/main/resources/dependency-updates-report.properties
Labels: maintenance

#823 [#767] display update information for ranges
  versions-common/src/main/java/org/codehaus/mojo/versions/api/AbstractVersionDetails.java
  versions-maven-plugin/src/it/it-823-ranges-update-report-001/invoker.properties
  versions-maven-plugin/src/it/it-823-ranges-update-report-001/pom.xml
  versions-maven-plugin/src/it/it-823-ranges-update-report-001/verify.groovy
  versions-maven-plugin/src/it/it-823-ranges-update-report-002/invoker.properties
  versions-maven-plugin/src/it/it-823-ranges-update-report-002/pom.xml
  versions-maven-plugin/src/it/it-823-ranges-update-report-002/verify.groovy
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/reporting/AbstractVersionsReportRenderer.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/reporting/PluginUpdatesReportRenderer.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/reporting/PropertyUpdatesReportRenderer.java
Labels: enhancement

#828 #704: Removing ArtifactResolver
  versions-common/src/main/java/org/codehaus/mojo/versions/api/DefaultVersionsHelper.java
  versions-common/src/main/java/org/codehaus/mojo/versions/api/VersionsHelper.java
  versions-common/src/test/java/org/codehaus/mojo/versions/api/DefaultVersionsHelperTest.java
  versions-enforcer/src/main/java/org/apache/maven/plugins/enforcer/MaxDependencyUpdates.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/AbstractVersionsDependencyUpdaterMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/AbstractVersionsDisplayMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/AbstractVersionsReport.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/AbstractVersionsUpdaterMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/CompareDependenciesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DependencyUpdatesReportMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayDependencyUpdatesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayParentUpdatesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayPluginUpdatesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayPropertyUpdatesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/ForceReleasesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/LockSnapshotsMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/ParentUpdatesReportMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/PluginUpdatesReportMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/PropertyUpdatesReportMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/ResolveRangesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/SetMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/SetPropertyMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/SetScmTagMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UnlockSnapshotsMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UpdateChildModulesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UpdateParentMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UpdatePropertiesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UpdatePropertyMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseDepVersionMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseLatestReleasesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseLatestSnapshotsMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseLatestVersionsMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseLatestVersionsMojoBase.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseNextReleasesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseNextSnapshotsMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseNextVersionsMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseReactorMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseReleasesMojo.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/DependencyUpdatesReportMojoTest.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/DisplayDependencyUpdatesMojoTest.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/ForceReleasesMojoTest.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/ParentUpdatesReportMojoTest.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/PluginUpdatesReportMojoTest.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/SeparatePatternsForIncludesAnExcludesTest.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/SetMojoTest.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/UpdateParentMojoTest.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/UpdatePropertiesMojoTestBase.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/UseLatestReleasesMojoTest.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/UseLatestVersionsMojoTest.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/UseReleasesMojoTest.java
  versions-test/src/main/java/org/codehaus/mojo/versions/utils/MockUtils.java
Labels: maintenance

#829 #704: Removing MavenProjectBuilder
  versions-common/src/main/java/org/codehaus/mojo/versions/api/PomHelper.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/AbstractVersionsDependencyUpdaterMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/AbstractVersionsDisplayMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/AbstractVersionsUpdaterMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/CompareDependenciesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayDependencyUpdatesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayParentUpdatesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayPluginUpdatesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayPropertyUpdatesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/ForceReleasesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/LockSnapshotsMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/ResolveRangesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/RevertMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/SetMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/SetPropertyMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/SetScmTagMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UnlockSnapshotsMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UpdateChildModulesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UpdateParentMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UpdatePropertiesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UpdatePropertyMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseDepVersionMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseLatestReleasesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseLatestSnapshotsMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseLatestVersionsMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseLatestVersionsMojoBase.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseNextReleasesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseNextSnapshotsMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseNextVersionsMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseReactorMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseReleasesMojo.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/DisplayDependencyUpdatesMojoTest.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/ForceReleasesMojoTest.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/SeparatePatternsForIncludesAnExcludesTest.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/UpdateParentMojoTest.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/UseLatestReleasesMojoTest.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/UseLatestVersionsMojoTest.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/UseReleasesMojoTest.java
Labels: maintenance
