Repository mojohaus/versions, pull requests merged in 2022-08, with the labels that each got.

#629 Reordering the checks in shouldApplyUpdate + a simple unit test
  src/main/java/org/codehaus/mojo/versions/AbstractVersionsUpdaterMojo.java
  src/test/java/org/codehaus/mojo/versions/UpdateParentMojoTest.java
Labels: bug

#630 New property: updateBuildOutputTimestampPolicy = (onchange | always | never) (#595)
  src/it/it-set-021-outputTimestampPolicy-always/invoker.properties
  src/it/it-set-021-outputTimestampPolicy-always/pom.xml
  src/it/it-set-021-outputTimestampPolicy-always/verify.groovy
  src/it/it-set-022-outputTimestampPolicy-onchange/invoker.properties
  src/it/it-set-022-outputTimestampPolicy-onchange/pom.xml
  src/it/it-set-022-outputTimestampPolicy-onchange/verify.groovy
  src/it/it-set-023-outputTimestampPolicy-never/invoker.properties
  src/it/it-set-023-outputTimestampPolicy-never/pom.xml
  src/it/it-set-023-outputTimestampPolicy-never/verify.groovy
  src/main/java/org/codehaus/mojo/versions/SetMojo.java
Labels: enhancement

#624 Replace deprecated ArtifactFactory by RepositorySystem
  src/main/java/org/codehaus/mojo/versions/AbstractVersionsDependencyUpdaterMojo.java
  src/main/java/org/codehaus/mojo/versions/AbstractVersionsReport.java
  src/main/java/org/codehaus/mojo/versions/AbstractVersionsUpdaterMojo.java
  src/main/java/org/codehaus/mojo/versions/DependencyUpdatesReport.java
  src/main/java/org/codehaus/mojo/versions/DisplayDependencyUpdatesMojo.java
  src/main/java/org/codehaus/mojo/versions/DisplayParentUpdatesMojo.java
  src/main/java/org/codehaus/mojo/versions/DisplayPluginUpdatesMojo.java
  src/main/java/org/codehaus/mojo/versions/LockSnapshotsMojo.java
  src/main/java/org/codehaus/mojo/versions/PluginUpdatesReport.java
  src/main/java/org/codehaus/mojo/versions/UpdateParentMojo.java
  src/main/java/org/codehaus/mojo/versions/UseReleasesMojo.java
  src/main/java/org/codehaus/mojo/versions/api/DefaultVersionsHelper.java
  src/main/java/org/codehaus/mojo/versions/api/PomHelper.java
  src/main/java/org/codehaus/mojo/versions/api/VersionsHelper.java
  src/test/java/org/codehaus/mojo/versions/api/DefaultVersionsHelperTest.java
Labels: maintenance

#639 Get rid of deprecated PathTranslator
  src/main/java/org/codehaus/mojo/versions/AbstractVersionsReport.java
  src/main/java/org/codehaus/mojo/versions/AbstractVersionsUpdaterMojo.java
  src/main/java/org/codehaus/mojo/versions/api/DefaultVersionsHelper.java
  src/main/java/org/codehaus/mojo/versions/utils/VersionsExpressionEvaluator.java
  src/test/java/org/codehaus/mojo/versions/api/DefaultVersionsHelperTest.java
Labels: maintenance

#643 Require Maven 3.2.5
  pom.xml
  src/main/java/org/codehaus/mojo/versions/DisplayPluginUpdatesMojo.java
  src/test/java/org/codehaus/mojo/versions/api/DefaultVersionsHelperTest.java
  src/test/java/org/codehaus/mojo/versions/ordering/VersionComparatorsTest.java
Labels: enhancement

#640 Limit to only artifacts that have updates and are in the dependency graph (#589)
  src/main/java/org/codehaus/mojo/versions/AbstractVersionsReport.java
  src/main/java/org/codehaus/mojo/versions/DependencyUpdatesReport.java
  src/main/java/org/codehaus/mojo/versions/PluginUpdatesReport.java
  src/main/java/org/codehaus/mojo/versions/utils/MiscUtils.java
  src/test/java/org/codehaus/mojo/versions/DependencyUpdatesReportTest.java
  src/test/java/org/codehaus/mojo/versions/PluginUpdatesReportTest.java
Labels: enhancement

#647 Cache result of getBestFitRule (fixes #575)
  src/it/it-property-updates-report-001/pom.xml
  src/it/it-property-updates-report-002-slow/invoker.properties
  src/it/it-property-updates-report-002-slow/maven-version-rules.xml
  src/it/it-property-updates-report-002-slow/pom.xml
  src/main/java/org/codehaus/mojo/versions/api/DefaultVersionsHelper.java
Labels: enhancement

#653 Fix for issue #323: using version range if currentVersion is not available for DependencyUpdatesXmlRenderer
  src/main/java/org/codehaus/mojo/versions/DependencyUpdatesXmlRenderer.java
  src/test/java/org/codehaus/mojo/versions/DependencyUpdatesXmlRendererTest.java
Labels: bug

#655 Fixing #604: npe in DependencyVersionChanger if artifact version is null
  src/it/it-set-024-versionless-dependency/child/pom.xml
  src/it/it-set-024-versionless-dependency/invoker.properties
  src/it/it-set-024-versionless-dependency/pom.xml
  src/main/java/org/codehaus/mojo/versions/SetMojo.java
Labels: bug

#656 Extension of AbstractMojoTestCase from maven testing harness: injecting projects w/o creating stubs
  src/test/java/org/codehaus/mojo/versions/utils/BaseMojoTestCase.java
Labels: maintenance

#660 Implementing #213: new argument: allowDowngrade, which will downgrade a snapshot if these are disallowed
  pom.xml
  src/main/java/org/codehaus/mojo/versions/UseLatestVersionsMojo.java
  src/main/java/org/codehaus/mojo/versions/api/AbstractVersionDetails.java
  src/main/java/org/codehaus/mojo/versions/api/PropertyVersions.java
  src/test/java/org/codehaus/mojo/versions/UseLatestVersionsMojoTest.java
Labels: enhancement

#661 Fixing #320: Correcting delta computation in ModifiedPomXMLEventReader
  src/main/java/org/codehaus/mojo/versions/rewriting/ModifiedPomXMLEventReader.java
  src/test/java/org/codehaus/mojo/versions/rewriting/ModifiedPomXMLEventReaderTest.java
Labels: bug

#663 #361: Typo in generated XML report for dependency updates
  src/main/java/org/codehaus/mojo/versions/DependencyUpdatesXmlRenderer.java
Labels: maintenance

#664 New feature (#477): connection, developerConnection, url arguments for set-scm-tag
  src/it/it-set-scm-tag-001/invoker.properties
  src/it/it-set-scm-tag-001/pom.xml
  src/it/it-set-scm-tag-001/verify.bsh
  src/it/it-set-scm-tag-001/verify.groovy
  src/main/java/org/codehaus/mojo/versions/SetScmTagMojo.java
Labels: enhancement
