Repository mojohaus/versions, pull requests merged in 2022-07, with the labels that each got.

#613 bugfix for parentVersion wrongly be String "null" when be missing and should be null be default
  src/main/java/org/codehaus/mojo/versions/UpdateParentMojo.java
Labels: bug

#617 Build project by Maven 3.2.5 and 3.8.6
  .github/workflows/maven.yml
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
Labels: build

#616 Fix for issue #582 - update-properties does not work across parent-child pom
  src/it-repo/dummy-parent-issue-582-1.0.pom
  src/it/it-update-properties-issue-582/invoker.properties
  src/it/it-update-properties-issue-582/pom.xml
  src/it/it-update-properties-issue-582/verify.groovy
  src/main/java/org/codehaus/mojo/versions/api/PomHelper.java
Labels: enhancement

#618 Cleanup project pom file
  pom.xml
  src/site/site.xml
Labels: maintenance

#623 Upgrade modello xmlns to 2.0.0 in rule.mdo
  src/main/mdo/rule.mdo
Labels: maintenance
