Repository mojohaus/versions, pull requests merged in 2023-05, with the labels that each got.

#908 Issue #74: Add display-extension-updates
  versions-common/pom.xml
  versions-common/src/main/java/org/codehaus/mojo/versions/api/DefaultVersionsHelper.java
  versions-common/src/main/java/org/codehaus/mojo/versions/api/VersionsHelper.java
  versions-common/src/main/java/org/codehaus/mojo/versions/filtering/DependencyFilter.java
  versions-common/src/main/java/org/codehaus/mojo/versions/utils/CoreExtensionUtils.java
  versions-common/src/main/java/org/codehaus/mojo/versions/utils/DependencyBuilder.java
  versions-common/src/main/java/org/codehaus/mojo/versions/utils/ExtensionBuilder.java
  versions-common/src/main/mdo/core-extensions.mdo
  versions-common/src/test/java/org/codehaus/mojo/versions/utils/CoreExtensionUtilsTest.java
  versions-common/src/test/resources/org/codehaus/mojo/versions/utils/core-extensions/.mvn/extensions.xml
  versions-maven-plugin/src/it/it-display-extension-updates-001/invoker.properties
  versions-maven-plugin/src/it/it-display-extension-updates-001/pom.xml
  versions-maven-plugin/src/it/it-display-extension-updates-001/verify.groovy
  versions-maven-plugin/src/it/it-display-extension-updates-002/.mvn/extensions.xml
  versions-maven-plugin/src/it/it-display-extension-updates-002/invoker.properties
  versions-maven-plugin/src/it/it-display-extension-updates-002/pom.xml
  versions-maven-plugin/src/it/it-display-extension-updates-002/verify.groovy
  versions-maven-plugin/src/it/it-display-extension-updates-003/.mvn/extensions.xml
  versions-maven-plugin/src/it/it-display-extension-updates-003/invoker.properties
  versions-maven-plugin/src/it/it-display-extension-updates-003/pom.xml
  versions-maven-plugin/src/it/it-display-extension-updates-003/verify.groovy
  versions-maven-plugin/src/it/it-display-extension-updates-004/child/.mvn/extensions.xml
  versions-maven-plugin/src/it/it-display-extension-updates-004/child/pom.xml
  versions-maven-plugin/src/it/it-display-extension-updates-004/invoker.properties
  versions-maven-plugin/src/it/it-display-extension-updates-004/pom.xml
  versions-maven-plugin/src/it/it-display-extension-updates-004/verify.groovy
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayExtensionUpdatesMojo.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/DependencyUpdatesReportMojoTest.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/DisplayExtensionUpdatesMojoTest.java
  versions-test/src/main/java/org/codehaus/mojo/versions/utils/MockUtils.java
Labels: enhancement

#955 Resolves #954: Excluded plexus-container-default
  pom.xml
Labels: bug

#953 Fix deprecated goals in ITs poms
  versions-enforcer/src/it/it-max-dependency-updates-001/pom.xml
  versions-enforcer/src/it/it-max-dependency-updates-002/pom.xml
  versions-enforcer/src/it/it-max-dependency-updates-003/pom.xml
  versions-enforcer/src/it/it-max-dependency-updates-004/pom.xml
  versions-enforcer/src/it/it-max-dependency-updates-005/pom.xml
  versions-enforcer/src/it/it-max-dependency-updates-006/pom.xml
Labels: maintenance

#924 Resolves #916: Partially reverted #799.
  versions-maven-plugin/src/it/it-set-005-properties/invoker.properties
  versions-maven-plugin/src/it/it-set-005-properties/module-a1/pom.xml
  versions-maven-plugin/src/it/it-set-005-properties/module-a2/pom.xml
  versions-maven-plugin/src/it/it-set-005-properties/pom.xml
  versions-maven-plugin/src/it/it-set-005-properties/verify.groovy
  versions-maven-plugin/src/it/it-set-005/verify.bsh
  versions-maven-plugin/src/it/it-set-005/verify.groovy
  versions-maven-plugin/src/it/it-set-issue-916-properties/invoker.properties
  versions-maven-plugin/src/it/it-set-issue-916-properties/pom.xml
  versions-maven-plugin/src/it/it-set-issue-916-properties/verify.groovy
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/SetMojo.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/SetMojoTest.java
  versions-maven-plugin/src/test/resources/org/codehaus/mojo/set/issue-855/pom-revision.xml
Labels: bug

#932 Resolves #931: Fixing problems with encoding in UseDepVersion and PomHelper
  versions-common/src/main/java/org/codehaus/mojo/versions/api/PomHelper.java
  versions-maven-plugin/src/it/it-use-dep-version-issue-931-umlauts-iso8859-1/invoker.properties
  versions-maven-plugin/src/it/it-use-dep-version-issue-931-umlauts-iso8859-1/pom.xml
  versions-maven-plugin/src/it/it-use-dep-version-issue-931-umlauts-iso8859-1/verify.groovy
  versions-maven-plugin/src/it/it-use-dep-version-issue-931-umlauts/invoker.properties
  versions-maven-plugin/src/it/it-use-dep-version-issue-931-umlauts/pom.xml
  versions-maven-plugin/src/it/it-use-dep-version-issue-931-umlauts/verify.groovy
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseDepVersionMojo.java
Labels: bug

#956 Resolves #921: Clarify dependencyIncludes/dependencyExcludes
  versions-enforcer/src/main/java/org/apache/maven/plugins/enforcer/MaxDependencyUpdates.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayDependencyUpdatesMojo.java
  versions-maven-plugin/src/site/markdown/examples/display-dependency-updates.md
  versions-maven-plugin/src/site/markdown/faq.md
Labels: documentation

#957 Use update policy DAILY instead of NEVER for remote repositories
  versions-common/src/main/java/org/codehaus/mojo/versions/api/DefaultVersionsHelper.java
  versions-common/src/test/java/org/codehaus/mojo/versions/api/DefaultVersionsHelperTest.java
Labels: enhancement
