Repository mojohaus/versions, pull requests merged in 2023-11, with the labels that each got.

#1023 Reading project model should throw exception
  versions-common/src/main/java/org/codehaus/mojo/versions/api/PomHelper.java
  versions-maven-plugin/pom.xml
  versions-maven-plugin/src/it/it-set-017-issue-321/module-a2/pom.invalid
  versions-maven-plugin/src/it/it-set-017-issue-321/setup.groovy
  versions-maven-plugin/src/it/it-set-017-issue-321/verify.bsh
  versions-maven-plugin/src/it/it-set-017-issue-321/verify.groovy
Labels: bug

#1024 Fix ISE with plugins aggregate report when reactor projects contains the same plugin declaration multiple time with different versions
  versions-common/src/main/java/org/codehaus/mojo/versions/api/PluginUpdatesDetails.java
  versions-common/src/main/java/org/codehaus/mojo/versions/utils/MiscUtils.java
  versions-maven-plugin/src/it/it-aggregate-plugn-multiple-versions-same-plugin/invoker.properties
  versions-maven-plugin/src/it/it-aggregate-plugn-multiple-versions-same-plugin/module-a1/pom.xml
  versions-maven-plugin/src/it/it-aggregate-plugn-multiple-versions-same-plugin/module-a2/pom.xml
  versions-maven-plugin/src/it/it-aggregate-plugn-multiple-versions-same-plugin/module-a3/pom.xml
  versions-maven-plugin/src/it/it-aggregate-plugn-multiple-versions-same-plugin/module-a4/pom.xml
  versions-maven-plugin/src/it/it-aggregate-plugn-multiple-versions-same-plugin/pom.xml
  versions-maven-plugin/src/it/it-aggregate-plugn-multiple-versions-same-plugin/verify.groovy
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/AbstractPluginUpdatesReportMojo.java
Labels: bug

#1017 Align update-parent and display-parent-update
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayParentUpdatesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UpdateParentMojo.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/DisplayParentUpdatesMojoTest.java
Labels: enhancement

#1026 update javadoc at-since annotation to 2.16.2
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayParentUpdatesMojo.java
Labels: documentation
