Repository mojohaus/versions, pull requests merged in 2023-01, with the labels that each got.

#893 Resolves #892: Restrict the ComparableVersion cache size
  pom.xml
  versions-common/pom.xml
  versions-common/src/main/java/org/codehaus/mojo/versions/ordering/ComparableVersion.java
Labels: enhancement

#882 Remove unnecessary synchronization in AbstractVersionDetails
  versions-common/src/main/java/org/codehaus/mojo/versions/api/AbstractVersionDetails.java
Labels: maintenance

#878 Resolves #474: Add property support to UseDepVersion
  versions-common/pom.xml
  versions-common/src/main/java/org/codehaus/mojo/versions/api/PomHelper.java
  versions-common/src/main/java/org/codehaus/mojo/versions/rewriting/ModifiedPomXMLEventReader.java
  versions-common/src/main/java/org/codehaus/mojo/versions/utils/MavenProjectUtils.java
  versions-common/src/main/java/org/codehaus/mojo/versions/utils/ModelNode.java
  versions-common/src/test/java/org/codehaus/mojo/versions/api/PomHelperTest.java
  versions-common/src/test/resources/org/codehaus/mojo/versions/api/findProperty/childA/grandchild/pom.xml
  versions-common/src/test/resources/org/codehaus/mojo/versions/api/findProperty/childA/pom.xml
  versions-common/src/test/resources/org/codehaus/mojo/versions/api/findProperty/childB/pom.xml
  versions-common/src/test/resources/org/codehaus/mojo/versions/api/findProperty/pom.xml
  versions-common/src/test/resources/org/codehaus/mojo/versions/api/getRawModelTree/childA/grandchild/pom.xml
  versions-common/src/test/resources/org/codehaus/mojo/versions/api/getRawModelTree/childA/pom.xml
  versions-common/src/test/resources/org/codehaus/mojo/versions/api/getRawModelTree/childB/pom.xml
  versions-common/src/test/resources/org/codehaus/mojo/versions/api/getRawModelTree/pom.xml
  versions-maven-plugin/src/it/it-use-dep-version-001/invoker.properties
  versions-maven-plugin/src/it/it-use-dep-version-001/pom.xml
  versions-maven-plugin/src/it/it-use-dep-version-001/verify.groovy
  versions-maven-plugin/src/it/it-use-dep-version-002/invoker.properties
  versions-maven-plugin/src/it/it-use-dep-version-002/it-use-dep-version-002-child/pom.xml
  versions-maven-plugin/src/it/it-use-dep-version-002/pom.xml
  versions-maven-plugin/src/it/it-use-dep-version-002/verify.groovy
  versions-maven-plugin/src/it/it-use-dep-version-003/invoker.properties
  versions-maven-plugin/src/it/it-use-dep-version-003/pom.xml
  versions-maven-plugin/src/it/it-use-dep-version-003/verify.groovy
  versions-maven-plugin/src/it/it-use-dep-version-004/invoker.properties
  versions-maven-plugin/src/it/it-use-dep-version-004/pom.xml
  versions-maven-plugin/src/it/it-use-dep-version-004/verify.groovy
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/AbstractDependencyUpdatesReportMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/AbstractVersionsUpdaterMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayPluginUpdatesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/ResolveRangesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseDepVersionMojo.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/UseDepVersionMojoTest.java
  versions-maven-plugin/src/test/resources/org/codehaus/mojo/use-dep-version/properties/child-parent-redefinition/child/pom.xml
  versions-maven-plugin/src/test/resources/org/codehaus/mojo/use-dep-version/properties/child-parent-redefinition/pom.xml
  versions-maven-plugin/src/test/resources/org/codehaus/mojo/use-dep-version/properties/child-parent/child/pom.xml
  versions-maven-plugin/src/test/resources/org/codehaus/mojo/use-dep-version/properties/child-parent/pom.xml
  versions-maven-plugin/src/test/resources/org/codehaus/mojo/use-dep-version/properties/conflict-cancellation-profiles/child/pom.xml
  versions-maven-plugin/src/test/resources/org/codehaus/mojo/use-dep-version/properties/conflict-cancellation-profiles/pom.xml
  versions-maven-plugin/src/test/resources/org/codehaus/mojo/use-dep-version/properties/conflict-cancellation/child/pom.xml
  versions-maven-plugin/src/test/resources/org/codehaus/mojo/use-dep-version/properties/conflict-cancellation/pom.xml
  versions-maven-plugin/src/test/resources/org/codehaus/mojo/use-dep-version/properties/conflict-redefinition/child/pom.xml
  versions-maven-plugin/src/test/resources/org/codehaus/mojo/use-dep-version/properties/conflict-redefinition/pom.xml
  versions-maven-plugin/src/test/resources/org/codehaus/mojo/use-dep-version/properties/conflict/pom.xml
  versions-maven-plugin/src/test/resources/org/codehaus/mojo/use-dep-version/properties/simple-profiles/pom.xml
  versions-maven-plugin/src/test/resources/org/codehaus/mojo/use-dep-version/properties/simple/pom.xml
Labels: enhancement

#886 Resolves #533: New parameter to DisplayPluginUpdatesMojo: processUnboundPlugins
  versions-maven-plugin/src/it/it-display-plugin-updates-issue-533/invoker.properties
  versions-maven-plugin/src/it/it-display-plugin-updates-issue-533/parent.xml
  versions-maven-plugin/src/it/it-display-plugin-updates-issue-533/pom.xml
  versions-maven-plugin/src/it/it-display-plugin-updates-issue-533/verify.groovy
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayPluginUpdatesMojo.java
Labels: enhancement

#887 Refactoring of DisplayPluginUpdates
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayPluginUpdatesMojo.java
Labels: maintenance

#889 Resolves #888: New optional parameter to SetMojo: interpolateProperties
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/SetMojo.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/SetMojoTest.java
Labels: enhancement

#897 Fixes #896: Fixing available version retrieval; enabling allowSnapshots
  versions-common/src/main/java/org/codehaus/mojo/versions/api/DefaultVersionsHelper.java
  versions-maven-plugin/src/it/it-display-parent-updates-no-updates/invoker.properties
  versions-maven-plugin/src/it/it-display-parent-updates-no-updates/pom.xml
  versions-maven-plugin/src/it/it-display-parent-updates-no-updates/verify.groovy
  versions-maven-plugin/src/it/it-display-parent-updates-simple-update/invoker.properties
  versions-maven-plugin/src/it/it-display-parent-updates-simple-update/pom.xml
  versions-maven-plugin/src/it/it-display-parent-updates-simple-update/verify.groovy
  versions-maven-plugin/src/it/it-display-parent-updates-snapshots/invoker.properties
  versions-maven-plugin/src/it/it-display-parent-updates-snapshots/pom.xml
  versions-maven-plugin/src/it/it-display-parent-updates-snapshots/verify.groovy
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayParentUpdatesMojo.java
Labels: bug

#901 Resolves #899: Corrected the invocation of Resolver to retrieve the timestamped snapshot version
  versions-maven-plugin/pom.xml
  versions-maven-plugin/src/it/it-lock-snapshots-junit5/invoker.properties
  versions-maven-plugin/src/it/it-lock-snapshots-junit5/pom.xml
  versions-maven-plugin/src/it/it-lock-snapshots-junit5/verify.groovy
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/LockSnapshotsMojo.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/LockSnapshotsMojoTest.java
Labels: bug

#898 Use ComparableVersion from Maven and remove the duplicate
  pom.xml
  versions-common/src/main/java/org/codehaus/mojo/versions/api/AbstractVersionDetails.java
  versions-common/src/main/java/org/codehaus/mojo/versions/api/DefaultVersionsHelper.java
  versions-common/src/main/java/org/codehaus/mojo/versions/api/PropertyVersions.java
  versions-common/src/main/java/org/codehaus/mojo/versions/filtering/WildcardMatcher.java
  versions-common/src/main/java/org/codehaus/mojo/versions/ordering/BoundArtifactVersion.java
  versions-common/src/main/java/org/codehaus/mojo/versions/ordering/ComparableVersion.java
  versions-common/src/main/java/org/codehaus/mojo/versions/ordering/MavenVersionComparator.java
  versions-common/src/main/java/org/codehaus/mojo/versions/ordering/MercuryVersionComparator.java
  versions-common/src/main/java/org/codehaus/mojo/versions/ordering/NumericVersionComparator.java
  versions-common/src/main/java/org/codehaus/mojo/versions/ordering/VersionComparators.java
  versions-common/src/main/java/org/codehaus/mojo/versions/utils/DefaultArtifactVersionCache.java
  versions-common/src/test/java/org/codehaus/mojo/versions/api/ArtifactVersionsTest.java
  versions-common/src/test/java/org/codehaus/mojo/versions/ordering/BoundArtifactVersionTest.java
  versions-common/src/test/java/org/codehaus/mojo/versions/ordering/MercuryVersionComparatorTest.java
  versions-common/src/test/java/org/codehaus/mojo/versions/ordering/VersionComparatorTestBase.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayPluginUpdatesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/MinimalMavenBuildVersionFinder.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UpdateParentMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseLatestVersionsMojoBase.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/AbstractVersionsUpdaterMojoTest.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/DependencyUpdatesXmlRendererTest.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/MinimalMavenBuildVersionFinderTest.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/PluginUpdatesXmlRendererTest.java
Labels: enhancement

#905 Prepare for Doxia 2.0.0
  pom.xml
  versions-maven-plugin/src/it/it-dependency-updates-aggregate-report-issue-333/src/site/site.xml
  versions-maven-plugin/src/it/it-dependency-updates-report-001/src/site/site.xml
  versions-maven-plugin/src/it/it-dependency-updates-report-002/src/site/site.xml
  versions-maven-plugin/src/it/it-dependency-updates-report-003/src/site/site.xml
  versions-maven-plugin/src/it/it-dependency-updates-report-004/src/site/site.xml
  versions-maven-plugin/src/it/it-parent-updates-report-001/src/site/site.xml
  versions-maven-plugin/src/it/it-plugin-updates-aggregate-report-issue-333/src/site/site.xml
  versions-maven-plugin/src/it/it-plugin-updates-report-001/src/site/site.xml
  versions-maven-plugin/src/it/it-plugin-updates-report-002/src/site/site.xml
  versions-maven-plugin/src/it/it-plugin-updates-report-003/src/site/site.xml
  versions-maven-plugin/src/it/it-property-updates-aggregate-report-issue-333/src/site/site.xml
  versions-maven-plugin/src/it/it-property-updates-report-001/src/site/site.xml
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/AbstractVersionsReport.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/reporting/AbstractVersionsReportRenderer.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/reporting/PluginUpdatesReportRenderer.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/reporting/PropertyUpdatesReportRenderer.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/reporting/VersionsReportRendererBase.java
Labels: enhancement

#910 Fix excluded IT test name
  pom.xml
  versions-maven-plugin/src/it/it-lock-snapshots-junit/invoker.properties
  versions-maven-plugin/src/it/it-lock-snapshots-junit/pom.xml
  versions-maven-plugin/src/it/it-lock-snapshots-junit/verify.groovy
Labels: maintenance
