Repository mojohaus/versions, pull requests merged in 2024-09, with the labels that each got.

#1132 Resolves #1131: Suppress logging when allowMajorUpdates, allowMinorUp…
  versions-common/src/main/java/org/codehaus/mojo/versions/utils/SegmentUtils.java
Labels: enhancement

#1133 bugix/ protect internal data in multi thread env.
  versions-common/src/main/java/org/codehaus/mojo/versions/api/ArtifactVersionsCache.java
  versions-common/src/main/java/org/codehaus/mojo/versions/api/DefaultVersionsHelper.java
Labels: bug

#1145 Fix #1144 / appends `.+` to `.+-(alpha|beta)`
  versions-maven-plugin/src/site/markdown/version-rules.md.vm
Labels: documentation
