Repository mojohaus/versions, pull requests merged in 2024-11, with the labels that each got.

#1174 Using Stax2 (Woodstox) instead of plexus-xml (Xpp) to process XML
  pom.xml
  versions-common/src/main/java/org/codehaus/mojo/versions/api/PomHelper.java
  versions-common/src/main/java/org/codehaus/mojo/versions/api/PropertyVersionsBuilder.java
  versions-common/src/main/java/org/codehaus/mojo/versions/change/AbstractVersionChanger.java
  versions-common/src/main/java/org/codehaus/mojo/versions/change/DependencyVersionChanger.java
  versions-common/src/main/java/org/codehaus/mojo/versions/change/ParentVersionChanger.java
  versions-common/src/main/java/org/codehaus/mojo/versions/change/PluginVersionChanger.java
  versions-common/src/main/java/org/codehaus/mojo/versions/change/ProjectVersionChanger.java
  versions-common/src/main/java/org/codehaus/mojo/versions/change/VersionChangerFactory.java
  versions-common/src/main/java/org/codehaus/mojo/versions/rewriting/ModifiedPomXMLEventReader.java
  versions-common/src/main/java/org/codehaus/mojo/versions/rewriting/MutableXMLStreamReader.java
  versions-common/src/main/java/org/codehaus/mojo/versions/utils/ModelNode.java
  versions-common/src/test/java/org/codehaus/mojo/versions/api/PomHelperTest.java
  versions-common/src/test/java/org/codehaus/mojo/versions/rewriting/ModifiedPomXMLEventReaderTest.java
  versions-common/src/test/java/org/codehaus/mojo/versions/rewriting/MutableXMLStreamReaderTest.java
  versions-common/src/test/java/org/codehaus/mojo/versions/utils/ModifiedPomXMLEventReaderUtils.java
  versions-common/src/test/resources/org/codehaus/mojo/versions/api/PomHelperTest.utf16.xml
  versions-common/src/test/resources/org/codehaus/mojo/versions/rewriting/iso-8859-2.xml
  versions-common/src/test/resources/org/codehaus/mojo/versions/rewriting/utf-16.xml
  versions-common/src/test/resources/org/codehaus/mojo/versions/rewriting/utf-8.xml
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/AbstractVersionsDependencyUpdaterMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/AbstractVersionsUpdaterMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/CompareDependenciesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayDependencyUpdatesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayExtensionUpdatesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayParentUpdatesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayPluginUpdatesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayPropertyUpdatesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/ForceReleasesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/LockSnapshotsMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/ResolveRangesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/SetMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/SetPropertyMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/SetScmTagMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UnlockSnapshotsMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UpdateChildModulesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UpdateParentMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UpdatePropertiesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UpdatePropertiesMojoBase.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UpdatePropertyMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseDepVersionMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseLatestReleasesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseLatestSnapshotsMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseLatestVersionsMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseLatestVersionsMojoBase.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseNextReleasesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseNextSnapshotsMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseNextVersionsMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseReactorMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseReleasesMojo.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/LockSnapshotsMojoTest.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/RewriteWithStAXTest.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/SeparatePatternsForIncludesAnExcludesTest.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/UpdatePropertiesMojoTestBase.java
Labels: maintenance

#1172 fix: Removed non-fully functional dynamic version goal
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-0-commits-0-tags/invoker.properties
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-0-commits-0-tags/pom.xml
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-0-commits-0-tags/selector.groovy
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-0-commits-0-tags/setup.groovy
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-0-commits-0-tags/verify.groovy
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-1-commit-0-tags/invoker.properties
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-1-commit-0-tags/pom.xml
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-1-commit-0-tags/selector.groovy
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-1-commit-0-tags/setup.groovy
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-1-commit-0-tags/verify.groovy
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-4-commits-1-vtag/invoker.properties
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-4-commits-1-vtag/pom.xml
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-4-commits-1-vtag/selector.groovy
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-4-commits-1-vtag/setup.groovy
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-4-commits-1-vtag/verify.groovy
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-latest-commit/invoker.properties
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-latest-commit/pom.xml
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-latest-commit/selector.groovy
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-latest-commit/setup.groovy
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-latest-commit/verify.groovy
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-param-append-snapshot/invoker.properties
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-param-append-snapshot/pom.xml
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-param-append-snapshot/selector.groovy
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-param-append-snapshot/setup.groovy
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-param-append-snapshot/verify.groovy
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-param-use-versions/invoker.properties
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-param-use-versions/pom.xml
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-param-use-versions/selector.groovy
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-param-use-versions/setup.groovy
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-param-use-versions/verify.groovy
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-property-name/invoker.properties
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-property-name/pom.xml
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-property-name/selector.groovy
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-property-name/setup.groovy
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-property-name/verify.groovy
  versions-maven-plugin/src/site/markdown/examples/use-dynamic-version-from-scm.md
  versions-maven-plugin/src/site/markdown/index.md
  versions-maven-plugin/src/site/site.xml
Labels: enhancement

#1176 Move to modello-stax
  versions-common/pom.xml
  versions-common/src/main/java/org/codehaus/mojo/versions/api/DefaultVersionsHelper.java
  versions-common/src/main/java/org/codehaus/mojo/versions/utils/CoreExtensionUtils.java
  versions-common/src/main/java/org/codehaus/mojo/versions/utils/RegexUtils.java
  versions-common/src/test/java/org/codehaus/mojo/versions/utils/CoreExtensionUtilsTest.java
  versions-common/src/test/resources/org/codehaus/mojo/versions/api/rules.xml
  versions-maven-plugin/pom.xml
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayExtensionUpdatesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/xml/DependencyUpdatesXmlReportRenderer.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/xml/PluginUpdatesXmlReportRenderer.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/xml/PropertyUpdatesXmlReportRenderer.java
  versions-model-report/pom.xml
  versions-model/pom.xml
  versions-model/src/main/mdo/rule.mdo
Labels: maintenance

#1177 Bump project version to 2.18.0-SNAPSHOT
  pom.xml
  versions-api/pom.xml
  versions-common/pom.xml
  versions-enforcer/pom.xml
  versions-maven-plugin/pom.xml
  versions-model-report/pom.xml
  versions-model/pom.xml
  versions-test/pom.xml
Labels: maintenance

#1178 Drop Maven Wrapper from project
  .mvn/README.txt
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  README.md
  mvnw
  mvnw.cmd
  mvnwDebug
  mvnwDebug.cmd
Labels: maintenance

#1179 Remove implementation of dynamic version goal
  versions-maven-plugin/pom.xml
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DynamicVersioningSCMPlugin.java
Labels: enhancement

#1181 Resolves #1060: Bugfix in UpdateParentMojo + add tests
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UpdateParentMojo.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/UpdateParentMojoTest.java
Labels: bug

#1180 Upgrade to Doxia 2.x stack
  pom.xml
  versions-enforcer/pom.xml
  versions-maven-plugin/pom.xml
  versions-maven-plugin/src/it/it-823-ranges-update-report-001/verify.groovy
  versions-maven-plugin/src/it/it-823-ranges-update-report-002/verify.groovy
  versions-maven-plugin/src/it/it-abstract-versions-report-001/verify.groovy
  versions-maven-plugin/src/it/it-aggregate-plugn-multiple-versions-same-plugin/verify.groovy
  versions-maven-plugin/src/it/it-dependency-updates-report-issue-684-001/verify.groovy
  versions-maven-plugin/src/it/it-display-parent-updates-no-updates/invoker.properties
  versions-maven-plugin/src/it/it-plugin-updates-report-issue-684-001/verify.groovy
  versions-maven-plugin/src/it/it-property-updates-report-issue-684-001/verify.groovy
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/AbstractDependencyUpdatesReport.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/AbstractPluginUpdatesReport.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/AbstractPropertyUpdatesReport.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/AbstractVersionsReport.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DependencyUpdatesAggregateReport.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DependencyUpdatesReport.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/ParentUpdatesReport.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/PluginUpdatesAggregateReport.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/PluginUpdatesReport.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/PropertyUpdatesAggregateReport.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/PropertyUpdatesReport.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/reporting/AbstractVersionsReportRenderer.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/reporting/DependencyUpdatesReportRenderer.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/reporting/PluginUpdatesReportRenderer.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/reporting/PropertyUpdatesReportRenderer.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/reporting/VersionsReportRendererBase.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/DependencyUpdatesReportTest.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/ParentUpdatesReportTest.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/PluginUpdatesReportTest.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/PropertyUpdatesReportTest.java
  versions-test/pom.xml
Labels: enhancement, dependencies

#1187 Fixes #1140: Added showVersionless (default true)
  versions-common/src/main/java/org/codehaus/mojo/versions/utils/DependencyBuilder.java
  versions-maven-plugin/src/it/it-display-dependency-updates-008-outputLineWidth/invoker.properties
  versions-maven-plugin/src/it/it-display-dependency-updates-008-outputLineWidth/pom.xml
  versions-maven-plugin/src/it/it-display-dependency-updates-008-outputLineWidth/verify.bsh
  versions-maven-plugin/src/it/it-display-dependency-updates-008/invoker.properties
  versions-maven-plugin/src/it/it-display-dependency-updates-008/pom.xml
  versions-maven-plugin/src/it/it-display-dependency-updates-008/verify.groovy
  versions-maven-plugin/src/it/it-display-dependency-updates-009-processDependencyManagementTransitive-false/invoker.properties
  versions-maven-plugin/src/it/it-display-dependency-updates-009-processDependencyManagementTransitive-false/verify.bsh
  versions-maven-plugin/src/it/it-display-dependency-updates-009-processDependencyManagementTransitive-true/invoker.properties
  versions-maven-plugin/src/it/it-display-dependency-updates-009-processDependencyManagementTransitive-true/pom.xml
  versions-maven-plugin/src/it/it-display-dependency-updates-009-processDependencyManagementTransitive-true/verify.bsh
  versions-maven-plugin/src/it/it-display-dependency-updates-009/invoker.properties
  versions-maven-plugin/src/it/it-display-dependency-updates-009/pom.xml
  versions-maven-plugin/src/it/it-display-dependency-updates-009/verify.groovy
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayDependencyUpdatesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayExtensionUpdatesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/internal/DependencyUpdatesLoggingHelper.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/DisplayDependencyUpdatesMojoTest.java
  versions-maven-plugin/src/test/resources/org/codehaus/mojo/display-dependency-updates/dependency-management-from-parent/child/pom.xml
  versions-maven-plugin/src/test/resources/org/codehaus/mojo/display-dependency-updates/dependency-management-from-parent/pom.xml
  versions-maven-plugin/src/test/resources/org/codehaus/mojo/display-dependency-updates/version-from-parent/child/pom.xml
  versions-maven-plugin/src/test/resources/org/codehaus/mojo/display-dependency-updates/version-from-parent/pom.xml
Labels: bug, enhancement

#1188 Fixes #1140 for reports
  versions-common/src/main/java/org/codehaus/mojo/versions/utils/DependencyComparator.java
  versions-common/src/main/java/org/codehaus/mojo/versions/utils/MavenProjectUtils.java
  versions-maven-plugin/src/it/it-dependency-updates-report-issue-1140/child/pom.xml
  versions-maven-plugin/src/it/it-dependency-updates-report-issue-1140/invoker.properties
  versions-maven-plugin/src/it/it-dependency-updates-report-issue-1140/pom.xml
  versions-maven-plugin/src/it/it-dependency-updates-report-issue-1140/verify.groovy
  versions-maven-plugin/src/it/it-display-dependency-updates-009-processDependencyManagementTransitive-true/verify.groovy
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/AbstractDependencyUpdatesReport.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DependencyUpdatesAggregateReport.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DependencyUpdatesReport.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayDependencyUpdatesMojo.java
Labels: bug

#1193 Fixed #1191: Processes (all) profiles from original model if transitive is false
  versions-common/src/main/java/org/codehaus/mojo/versions/utils/MavenProjectUtils.java
  versions-maven-plugin/src/it/it-changerecord-update-parent-001/verify.groovy
  versions-maven-plugin/src/it/it-changerecord-update-properties-001/verify.groovy
  versions-maven-plugin/src/it/it-changerecord-use-latest-releases-001/verify.groovy
  versions-maven-plugin/src/it/it-changerecord-use-latest-snapshots-001/verify.groovy
  versions-maven-plugin/src/it/it-changerecord-use-latest-versions-001/verify.groovy
  versions-maven-plugin/src/it/it-changerecord-use-next-versions-001/verify.groovy
  versions-maven-plugin/src/it/it-dependency-updates-report-issue-1191/invoker.properties
  versions-maven-plugin/src/it/it-dependency-updates-report-issue-1191/pom.xml
  versions-maven-plugin/src/it/it-dependency-updates-report-issue-1191/verify.groovy
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/AbstractDependencyUpdatesReport.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayDependencyUpdatesMojo.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/DependencyUpdatesReportTest.java
  versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/DisplayDependencyUpdatesMojoTest.java
  versions-maven-plugin/src/test/resources/org/codehaus/mojo/display-dependency-updates/profiles/pom.xml
Labels: bug

#1194 Fixed the failed release build
  versions-maven-plugin/src/it-repo/dummy-aggregate-child-1.0.1.pom
  versions-maven-plugin/src/it-repo/dummy-aggregate-parent-1.0.1.pom
  versions-maven-plugin/src/it/it-dependency-updates-aggregate-report-issue-333/child-one/pom.xml
  versions-maven-plugin/src/it/it-dependency-updates-aggregate-report-issue-333/child-two/pom.xml
  versions-maven-plugin/src/it/it-dependency-updates-aggregate-report-issue-333/invoker.properties
  versions-maven-plugin/src/it/it-dependency-updates-aggregate-report-issue-333/pom.xml
  versions-maven-plugin/src/it/it-dependency-updates-aggregate-report-issue-333/verify.groovy
  versions-maven-plugin/src/it/it-plugin-updates-aggregate-report-issue-333/child-one/pom.xml
  versions-maven-plugin/src/it/it-plugin-updates-aggregate-report-issue-333/child-two/pom.xml
  versions-maven-plugin/src/it/it-plugin-updates-aggregate-report-issue-333/invoker.properties
  versions-maven-plugin/src/it/it-plugin-updates-aggregate-report-issue-333/pom.xml
  versions-maven-plugin/src/it/it-plugin-updates-aggregate-report-issue-333/verify.groovy
  versions-maven-plugin/src/it/it-property-updates-aggregate-report-issue-333/child-one/pom.xml
  versions-maven-plugin/src/it/it-property-updates-aggregate-report-issue-333/child-two/pom.xml
  versions-maven-plugin/src/it/it-property-updates-aggregate-report-issue-333/invoker.properties
  versions-maven-plugin/src/it/it-property-updates-aggregate-report-issue-333/pom.xml
  versions-maven-plugin/src/it/it-property-updates-aggregate-report-issue-333/verify.groovy
Labels: bug
