Repository mojohaus/versions, pull requests merged in 2024-06, with the labels that each got.

#1088 Build ITs in parallel
  pom.xml
  versions-enforcer/pom.xml
  versions-enforcer/src/it/settings.xml
  versions-maven-plugin/pom.xml
  versions-maven-plugin/src/it/settings.xml
Labels: build

#1089 Require Maven 3.6.3, dependencies cleanups
  README.md
  pom.xml
  versions-api/pom.xml
  versions-common/pom.xml
  versions-enforcer/pom.xml
  versions-maven-plugin/pom.xml
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayParentUpdatesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/SetMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UpdateParentMojo.java
  versions-model-report/pom.xml
  versions-model/pom.xml
  versions-test/pom.xml
Labels: enhancement

#1093 Add range type in ignoreVersion
  pom.xml
  versions-common/pom.xml
  versions-common/src/main/java/org/codehaus/mojo/versions/api/DefaultVersionsHelper.java
  versions-common/src/main/java/org/codehaus/mojo/versions/api/IgnoreVersionHelper.java
  versions-common/src/main/java/org/codehaus/mojo/versions/utils/DefaultArtifactVersionCache.java
  versions-common/src/test/java/org/codehaus/mojo/versions/api/IgnoreVersionHelperTest.java
  versions-enforcer/src/main/java/org/codehaus/mojo/versions/enforcer/MaxDependencyUpdates.java
  versions-maven-plugin/src/it/it-display-dependency-updates-issue-684-pom-based-rules/pom.xml
  versions-maven-plugin/src/it/it-display-dependency-updates-issue-684-pom-based-rules/verify.groovy
  versions-maven-plugin/src/it/it-encoding-001/verify.bsh
  versions-maven-plugin/src/it/it-encoding-001/verify.groovy
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/AbstractVersionsReport.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/AbstractVersionsUpdaterMojo.java
  versions-maven-plugin/src/site/markdown/version-rules.md.vm
  versions-model/src/main/mdo/rule.mdo
Labels: enhancement

#1094 Use JUnit5 in versions-commons, versions-enforcer
  pom.xml
  versions-common/pom.xml
  versions-common/src/main/java/org/codehaus/mojo/versions/api/AbstractVersionDetails.java
  versions-common/src/main/java/org/codehaus/mojo/versions/api/DefaultVersionsHelper.java
  versions-common/src/test/java/org/codehaus/mojo/versions/api/AbstractVersionDetailsTest.java
  versions-common/src/test/java/org/codehaus/mojo/versions/api/ArtifactVersionsTest.java
  versions-common/src/test/java/org/codehaus/mojo/versions/api/DefaultVersionsHelperTest.java
  versions-common/src/test/java/org/codehaus/mojo/versions/api/PomHelperTest.java
  versions-common/src/test/java/org/codehaus/mojo/versions/ordering/BoundArtifactVersionTest.java
  versions-common/src/test/java/org/codehaus/mojo/versions/ordering/MavenVersionComparatorTest.java
  versions-common/src/test/java/org/codehaus/mojo/versions/ordering/MercuryVersionComparatorTest.java
  versions-common/src/test/java/org/codehaus/mojo/versions/ordering/NumericVersionComparatorTest.java
  versions-common/src/test/java/org/codehaus/mojo/versions/ordering/VersionComparatorTestBase.java
  versions-common/src/test/java/org/codehaus/mojo/versions/recording/ChangeRecorderXMLTest.java
  versions-common/src/test/java/org/codehaus/mojo/versions/rewriting/ModifiedPomXMLEventReaderTest.java
  versions-common/src/test/java/org/codehaus/mojo/versions/utils/CoreExtensionUtilsTest.java
  versions-common/src/test/java/org/codehaus/mojo/versions/utils/PropertiesVersionsFileReaderTest.java
  versions-common/src/test/java/org/codehaus/mojo/versions/utils/SegmentUtilsTest.java
  versions-common/src/test/java/org/codehaus/mojo/versions/utils/VersionStub.java
  versions-enforcer/pom.xml
  versions-enforcer/src/test/java/org/codehaus/mojo/versions/enforcer/MaxDependencyUpdatesTest.java
  versions-maven-plugin/src/it/it-set-issue-505/invoker.properties
  versions-maven-plugin/src/it/it-set-issue-505/moduleA/moduleB/pom.xml
  versions-maven-plugin/src/it/it-set-issue-505/moduleA/pom.xml
  versions-maven-plugin/src/it/it-set-issue-505/pom.xml
  versions-maven-plugin/src/it/it-set-issue-505/verify.groovy
  versions-test/pom.xml
  versions-test/src/main/java/org/codehaus/mojo/versions/utils/MockUtils.java
  versions-test/src/main/java/org/codehaus/mojo/versions/utils/VersionStub.java
Labels: maintenance

#1096 Execute fail-fast job without ITs
  .github/workflows/maven.yml
Labels: build

#1097 Optimize ITs parallel build
  versions-enforcer/src/it/it-max-dependency-updates-001/invoker.properties
  versions-maven-plugin/src/it/setup-smoke-test/invoker.properties
  versions-maven-plugin/src/it/setup-smoke-test/pom.xml
Labels: build

#1095 Remove unmaintained changes.xml
  versions-maven-plugin/src/changes/changes.xml
Labels: maintenance

#1082 feat: Add Dynamic Versioning SCM plugin
  versions-maven-plugin/pom.xml
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-0-commits-0-tags/invoker.properties
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-0-commits-0-tags/pom.xml
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-0-commits-0-tags/selector.groovy
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-0-commits-0-tags/setup.groovy
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-0-commits-0-tags/verify.groovy
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-1-commit-0-tags/invoker.properties
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-1-commit-0-tags/pom.xml
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-1-commit-0-tags/selector.groovy
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-1-commit-0-tags/setup.groovy
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-1-commit-0-tags/verify.groovy
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-4-commits-1-vtag/invoker.properties
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-4-commits-1-vtag/pom.xml
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-4-commits-1-vtag/selector.groovy
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-4-commits-1-vtag/setup.groovy
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-4-commits-1-vtag/verify.groovy
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-latest-commit/invoker.properties
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-latest-commit/pom.xml
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-latest-commit/selector.groovy
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-latest-commit/setup.groovy
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-latest-commit/verify.groovy
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-param-append-snapshot/invoker.properties
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-param-append-snapshot/pom.xml
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-param-append-snapshot/selector.groovy
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-param-append-snapshot/setup.groovy
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-param-append-snapshot/verify.groovy
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-param-use-versions/invoker.properties
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-param-use-versions/pom.xml
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-param-use-versions/selector.groovy
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-param-use-versions/setup.groovy
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-param-use-versions/verify.groovy
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-property-name/invoker.properties
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-property-name/pom.xml
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-property-name/selector.groovy
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-property-name/setup.groovy
  versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-property-name/verify.groovy
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DynamicVersioningSCMPlugin.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/VersionInformation.java
  versions-maven-plugin/src/site/markdown/examples/use-dynamic-version-from-scm.md
  versions-maven-plugin/src/site/markdown/index.md
Labels: enhancement

#1100 Build and test with Maven 4
  .github/workflows/maven.yml
Labels: build
