Repository mojohaus/versions, pull requests merged in 2025-09, with the labels that each got.

#1264 Remove manual default from docs for parameters
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayDependencyUpdatesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayExtensionUpdatesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseDepVersionMojo.java
Labels: maintenance

#1275 Resolves #1271: Fixed broken Site links
  versions-maven-plugin/src/site/markdown/index.md
Labels: documentation

#1274 Resolves #1266: Applying the include filter during association resolution
  versions-common/src/main/java/org/codehaus/mojo/versions/api/DefaultVersionsHelper.java
  versions-common/src/main/java/org/codehaus/mojo/versions/api/PropertyVersionsBuilder.java
  versions-common/src/main/java/org/codehaus/mojo/versions/api/VersionsHelper.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UpdatePropertiesMojo.java
  versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UpdatePropertiesMojoBase.java
Labels: bug

#1281 Artifact comparison should use semantic version comparison.
  versions-common/src/main/java/org/codehaus/mojo/versions/utils/DependencyComparator.java
  versions-common/src/main/java/org/codehaus/mojo/versions/utils/PluginComparator.java
  versions-common/src/main/java/org/codehaus/mojo/versions/utils/PropertyComparator.java
  versions-common/src/main/java/org/codehaus/mojo/versions/utils/VersionStringComparator.java
  versions-common/src/test/java/org/codehaus/mojo/versions/utils/DependencyComparatorTest.java
  versions-common/src/test/java/org/codehaus/mojo/versions/utils/PluginComparatorTest.java
Labels: bug
